/**
 * AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
 * Generated by scripts/generate-blog-manifest.mjs
 */
import * as m0 from "./articles/best-tools-for-paycheck-planning-usa";
import * as m1 from "./articles/business-loan-lender-scan";
import * as m2 from "./articles/credit-card-payoff-strategies";
import * as m3 from "./articles/emi-explained";
import * as m4 from "./articles/emi-loan";
import * as m5 from "./articles/home-equity-usa-borrow";
import * as m6 from "./articles/hourly-vs-salary";
import * as m7 from "./articles/how-to-calculate-mortgage-payment-with-taxes-and-insurance";
import * as m8 from "./articles/how-to-compare-rent-vs-buy-without-hype";
import * as m9 from "./articles/how-to-estimate-take-home-pay-from-gross-salary";
import * as m10 from "./articles/medical-malpractice-basics";
import * as m11 from "./articles/mortgage-payment-usa-piti";
import * as m12 from "./articles/personal-injury-settlement-reality";
import * as m13 from "./articles/refinance-break-even-usa";
import * as m14 from "./articles/rent-vs-buy-usa";
import * as m15 from "./articles/roi-business";
import * as m16 from "./articles/roi-calculator-explained-for-marketing-campaigns";
import * as m17 from "./articles/roi-simple";
import * as m18 from "./articles/salary-after-tax-usa";
import * as m19 from "./articles/student-loan-forgiveness-roadmap";
import * as m20 from "./articles/tool-seo-expansion";

export const BLOG_ARTICLE_MODULE_ENTRIES = [
  { sourceFile: "best-tools-for-paycheck-planning-usa.tsx", module: m0 },
  { sourceFile: "business-loan-lender-scan.tsx", module: m1 },
  { sourceFile: "credit-card-payoff-strategies.tsx", module: m2 },
  { sourceFile: "emi-explained.tsx", module: m3 },
  { sourceFile: "emi-loan.tsx", module: m4 },
  { sourceFile: "home-equity-usa-borrow.tsx", module: m5 },
  { sourceFile: "hourly-vs-salary.tsx", module: m6 },
  { sourceFile: "how-to-calculate-mortgage-payment-with-taxes-and-insurance.tsx", module: m7 },
  { sourceFile: "how-to-compare-rent-vs-buy-without-hype.tsx", module: m8 },
  { sourceFile: "how-to-estimate-take-home-pay-from-gross-salary.tsx", module: m9 },
  { sourceFile: "medical-malpractice-basics.tsx", module: m10 },
  { sourceFile: "mortgage-payment-usa-piti.tsx", module: m11 },
  { sourceFile: "personal-injury-settlement-reality.tsx", module: m12 },
  { sourceFile: "refinance-break-even-usa.tsx", module: m13 },
  { sourceFile: "rent-vs-buy-usa.tsx", module: m14 },
  { sourceFile: "roi-business.tsx", module: m15 },
  { sourceFile: "roi-calculator-explained-for-marketing-campaigns.tsx", module: m16 },
  { sourceFile: "roi-simple.tsx", module: m17 },
  { sourceFile: "salary-after-tax-usa.tsx", module: m18 },
  { sourceFile: "student-loan-forgiveness-roadmap.tsx", module: m19 },
  { sourceFile: "tool-seo-expansion.tsx", module: m20 },
] as const;
