/**
 * AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
 * Generated by scripts/generate-blog-manifest.mjs
 */
import * as m0 from "./articles/ai-content-humanizer-natural-text-guide";
import * as m1 from "./articles/best-tools-for-paycheck-planning-usa";
import * as m2 from "./articles/break-even-analysis-formula-examples-calculator";
import * as m3 from "./articles/business-loan-lender-scan";
import * as m4 from "./articles/credit-card-payoff-strategies";
import * as m5 from "./articles/emi-explained";
import * as m6 from "./articles/emi-loan";
import * as m7 from "./articles/home-equity-usa-borrow";
import * as m8 from "./articles/hourly-vs-salary";
import * as m9 from "./articles/how-to-calculate-emi-formula-examples-free-calculator";
import * as m10 from "./articles/how-to-calculate-mortgage-payment-with-taxes-and-insurance";
import * as m11 from "./articles/how-to-calculate-take-home-salary-country-guide";
import * as m12 from "./articles/how-to-compare-rent-vs-buy-without-hype";
import * as m13 from "./articles/how-to-estimate-take-home-pay-from-gross-salary";
import * as m14 from "./articles/how-to-merge-pdf-files-for-free";
import * as m15 from "./articles/loan-calculator-how-banks-calculate-your-emi";
import * as m16 from "./articles/medical-malpractice-basics";
import * as m17 from "./articles/merge-pdf-files-free-five-methods-compared";
import * as m18 from "./articles/mortgage-payment-usa-piti";
import * as m19 from "./articles/net-worth-calculator-five-minute-guide";
import * as m20 from "./articles/personal-injury-settlement-reality";
import * as m21 from "./articles/refinance-break-even-usa";
import * as m22 from "./articles/rent-vs-buy-usa";
import * as m23 from "./articles/roi-business";
import * as m24 from "./articles/roi-calculator-explained-for-marketing-campaigns";
import * as m25 from "./articles/roi-calculator-measure-return-on-investment";
import * as m26 from "./articles/roi-simple";
import * as m27 from "./articles/salary-after-tax-take-home-country-comparison-guide";
import * as m28 from "./articles/salary-after-tax-usa";
import * as m29 from "./articles/student-loan-forgiveness-roadmap";
import * as m30 from "./articles/tool-seo-expansion";
import * as m31 from "./articles/vat-calculator-guide-small-businesses";
import * as m32 from "./articles/vat-calculator-uk-eu-uae-add-remove-guide";

export const BLOG_ARTICLE_MODULE_ENTRIES = [
  { sourceFile: "ai-content-humanizer-natural-text-guide.tsx", module: m0 },
  { sourceFile: "best-tools-for-paycheck-planning-usa.tsx", module: m1 },
  { sourceFile: "break-even-analysis-formula-examples-calculator.tsx", module: m2 },
  { sourceFile: "business-loan-lender-scan.tsx", module: m3 },
  { sourceFile: "credit-card-payoff-strategies.tsx", module: m4 },
  { sourceFile: "emi-explained.tsx", module: m5 },
  { sourceFile: "emi-loan.tsx", module: m6 },
  { sourceFile: "home-equity-usa-borrow.tsx", module: m7 },
  { sourceFile: "hourly-vs-salary.tsx", module: m8 },
  { sourceFile: "how-to-calculate-emi-formula-examples-free-calculator.tsx", module: m9 },
  { sourceFile: "how-to-calculate-mortgage-payment-with-taxes-and-insurance.tsx", module: m10 },
  { sourceFile: "how-to-calculate-take-home-salary-country-guide.tsx", module: m11 },
  { sourceFile: "how-to-compare-rent-vs-buy-without-hype.tsx", module: m12 },
  { sourceFile: "how-to-estimate-take-home-pay-from-gross-salary.tsx", module: m13 },
  { sourceFile: "how-to-merge-pdf-files-for-free.tsx", module: m14 },
  { sourceFile: "loan-calculator-how-banks-calculate-your-emi.tsx", module: m15 },
  { sourceFile: "medical-malpractice-basics.tsx", module: m16 },
  { sourceFile: "merge-pdf-files-free-five-methods-compared.tsx", module: m17 },
  { sourceFile: "mortgage-payment-usa-piti.tsx", module: m18 },
  { sourceFile: "net-worth-calculator-five-minute-guide.tsx", module: m19 },
  { sourceFile: "personal-injury-settlement-reality.tsx", module: m20 },
  { sourceFile: "refinance-break-even-usa.tsx", module: m21 },
  { sourceFile: "rent-vs-buy-usa.tsx", module: m22 },
  { sourceFile: "roi-business.tsx", module: m23 },
  { sourceFile: "roi-calculator-explained-for-marketing-campaigns.tsx", module: m24 },
  { sourceFile: "roi-calculator-measure-return-on-investment.tsx", module: m25 },
  { sourceFile: "roi-simple.tsx", module: m26 },
  { sourceFile: "salary-after-tax-take-home-country-comparison-guide.tsx", module: m27 },
  { sourceFile: "salary-after-tax-usa.tsx", module: m28 },
  { sourceFile: "student-loan-forgiveness-roadmap.tsx", module: m29 },
  { sourceFile: "tool-seo-expansion.tsx", module: m30 },
  { sourceFile: "vat-calculator-guide-small-businesses.tsx", module: m31 },
  { sourceFile: "vat-calculator-uk-eu-uae-add-remove-guide.tsx", module: m32 },
] as const;
