/** Curated blog slugs per marketing hub (directory group). */
export const HUB_FEATURED_BLOG_SLUGS: Record<string, readonly string[]> = {
  finance: [
    "how-to-calculate-emi-formula-examples-free-calculator",
    "how-to-calculate-take-home-salary-country-guide",
    "salary-after-tax-take-home-country-comparison-guide",
    "loan-calculator-how-banks-calculate-your-emi",
    "how-to-estimate-take-home-pay-from-gross-salary",
    "emi-calculation-explained",
    "best-tools-for-paycheck-planning-usa",
    "uk-self-employed-dividend-salary-effective-percent-toollabz",
    "gst-australia-inclusive-exclusive-10-percent-small-business",
    "gst-vs-vat-uk-au-cross-border-pricing-toollabz",
    "zakat-calculation-nisab-practical-guide-respectful",
  ],
  "real-estate": ["rent-vs-buy-usa-guide", "how-to-compare-rent-vs-buy-without-hype", "mortgage-payment-usa-piti-escrow-guide"],
  "business-saas": [
    "break-even-analysis-formula-examples-calculator",
    "vat-calculator-uk-eu-uae-add-remove-guide",
    "how-to-calculate-roi-business",
    "business-loan-what-lenders-scan-first",
    "roi-calculator-explained-for-marketing-campaigns",
    "saas-roas-churn-retention-metrics-primer-toollabz",
    "marketplace-seller-fees-stripe-paypal-etsy-ebay-toollabz",
    "employee-loaded-cost-pricing-seat-economics-toollabz",
  ],
  ai: ["ai-content-humanizer-natural-text-guide", "tool-seo-expansion"],
  utility: [
    "tool-seo-expansion",
    "working-days-uk-timezones-business-slas-toollabz",
    "imperial-metric-stone-feet-acres-hectares-conversion-guide",
  ],
  pdf: ["merge-pdf-files-free-five-methods-compared", "how-to-merge-pdf-files-for-free", "vat-calculator-guide-small-businesses"],
  developer: [
    "tool-seo-expansion",
    "developer-text-json-yaml-html-csv-pipeline-toollabz",
    "jwt-expiry-api-healthchecks-curl-playbook-toollabz",
    "json-formatting-and-validation-explained-developer",
    "jwt-token-decode-vs-verify-security-guide-toollabz",
    "sql-cron-readability-schedulers-developer-guide-toollabz",
    "regex-beginner-guide-practical-patterns-toollabz",
  ],
  marketing: ["roi-calculator-measure-return-on-investment", "roi-calculator-explained-for-marketing-campaigns", "how-to-calculate-roi"],
};
