import type { ToolDefinition } from "./types";

/**
 * Phase 1 SEO expansion: new production tools (clusters: developer, finance AU/Zakat, business ops, converters).
 * Slugs here must have compute logic in `expansion-phase1-compute.ts` and SEO profiles in `phase1-seo-expansion-batch1.ts`.
 */
export const expansionPhase1ToolDefinitions: ToolDefinition[] = [
  {
    slug: "jwt-decoder",
    name: "JWT Decoder (Header & Payload)",
    shortDescription: "Decode JWT header and payload safely in your browser.",
    description:
      "Paste a JSON Web Token to inspect Base64URL-decoded header and payload JSON. Shows exp/nbf as human-readable UTC when present. Does not verify signatures or claims; use your auth stack for trust decisions.",
    category: "developer",
    fields: [{ name: "jwt", label: "JWT (paste token)", type: "textarea", placeholder: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..." }],
    keywords: ["jwt decoder", "decode jwt online", "jwt payload viewer", "inspect jwt without verify", "jwt exp decoder"],
    howToUse: [
      "Paste a complete JWT (three dot-separated segments).",
      "Click Calculate to decode header and payload JSON.",
      "Review standard time claims (exp, nbf, iat) when present.",
      "Never treat decoded output as proof of authenticity; verification requires the issuer’s secret or public key.",
    ],
    faqs: [
      {
        question: "Does this verify the JWT signature?",
        answer: "No. Signature verification needs your server keys and algorithm policy; this tool only decodes readable segments.",
      },
      {
        question: "Why does decoding fail?",
        answer: "Tokens must be three Base64URL segments. Truncated, encrypted (JWE), or malformed tokens will error clearly.",
      },
      {
        question: "Is it safe to paste production tokens?",
        answer: "Processing is in-browser on Toollabz; still avoid pasting highly sensitive tokens on shared devices.",
      },
      {
        question: "What about encrypted JWE tokens?",
        answer: "This decoder targets signed JWT (JWS) layout. JWE payloads are not supported here.",
      },
      {
        question: "Can I see custom claims?",
        answer: "Yes; any JSON claims in the payload appear in the formatted output.",
      },
    ],
    related: ["json-validator", "json-formatter", "base64-encoder-decoder", "unix-timestamp-converter", "regex-tester"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator (v4)",
    shortDescription: "Generate cryptographically random UUID v4 values.",
    description:
      "Create RFC 4122 version 4 UUIDs using the browser’s random source. Useful for IDs, correlation keys, fixtures, and local testing.",
    category: "developer",
    fields: [
      { name: "count", label: "How many UUIDs (1–50)", type: "number", min: 1, step: 1 },
      { name: "uppercase", label: "Uppercase hex", type: "select", options: [{ label: "Lowercase (default)", value: "lower" }, { label: "Uppercase", value: "upper" }] },
    ],
    keywords: ["uuid generator", "uuid v4 generator online", "random uuid", "generate guid", "bulk uuid generator"],
    howToUse: ["Choose how many UUIDs you need (up to 50 per run).", "Pick uppercase or lowercase hex formatting.", "Click Calculate and copy lines into code, configs, or tickets."],
    faqs: [
      { question: "Are UUIDs guaranteed unique?", answer: "Collision risk is negligible for v4; still enforce DB uniqueness if required." },
      { question: "Does this support UUID v7?", answer: "Only v4 random is generated here; v7 is time-sortable and not implemented in this tool." },
      { question: "Can I use these in production databases?", answer: "Yes for typical surrogate keys; follow your platform’s ID strategy and indexing guidance." },
      { question: "Why limit 50 per click?", answer: "Keeps the page responsive; run again for more batches." },
      { question: "Is this cryptographically secure?", answer: "It uses crypto.randomUUID when available; suitable for identifiers; not a substitute for key generation workflows." },
    ],
    related: ["jwt-decoder", "json-validator", "sql-formatter", "cron-expression-generator", "markdown-to-html-converter"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter (Readability)",
    shortDescription: "Indent and normalize simple SELECT-style SQL for readability.",
    description:
      "Improve readability of common SQL with keyword line breaks and light indentation. Best for ad-hoc queries and docs; always review before running against production.",
    category: "developer",
    fields: [{ name: "sql", label: "SQL", type: "textarea", placeholder: "SELECT a,b FROM t WHERE id=1" }],
    keywords: ["sql formatter online", "format sql query", "sql beautifier", "indent sql", "pretty print sql"],
    howToUse: ["Paste SQL into the text area.", "Click Calculate for a formatted draft.", "Manually verify strings and dialect-specific syntax after formatting."],
    faqs: [
      { question: "Does this understand every SQL dialect?", answer: "No; it applies generic rules; PL/pgSQL blocks, CTE edge cases, or vendor extensions may need manual touch-up." },
      { question: "Will this change my query semantics?", answer: "It should not, but you should always re-run validation in your SQL client or CI." },
      { question: "Can it minify SQL?", answer: "This tool focuses on readability (expand), not minification." },
      { question: "Does it format INSERT batches?", answer: "Partially; very large dumps are better handled in an editor or dedicated formatter." },
      { question: "Is my SQL sent to a server?", answer: "No; formatting runs locally in your browser session." },
    ],
    related: ["json-validator", "regex-tester", "jwt-decoder", "api-response-formatter", "markdown-to-html-converter"],
  },
  {
    slug: "cron-expression-generator",
    name: "Cron Expression Helper (5-field)",
    shortDescription: "Summarize standard 5-field cron strings (minute hour dom month dow).",
    description:
      "Paste a cron schedule to get a human-readable field-by-field summary. Supports common numbers, ranges, steps, and * wildcards. Does not connect to schedulers; use for documentation and quick sanity checks.",
    category: "developer",
    fields: [{ name: "cron", label: "Cron expression", type: "text", placeholder: "0 9 * * 1-5" }],
    keywords: ["cron expression generator", "cron helper online", "crontab explain", "5 field cron summary", "schedule string decoder"],
    howToUse: ["Enter five fields separated by spaces (minute hour day-of-month month day-of-week).", "Click Calculate for a readable breakdown.", "Confirm semantics in your orchestrator (Kubernetes, systemd, Quartz, etc.)."],
    faqs: [
      { question: "Does this validate against my cloud cron?",
        answer: "Different systems extend cron differently; treat output as explanatory, not authoritative.",
      },
      { question: "Are seconds supported?",
        answer: "No; classic 5-field Unix cron omits a seconds column; some platforms add a sixth field separately.",
      },
      { question: "What about @yearly or @daily macros?",
        answer: "Macros are not expanded here; convert to numeric fields first if needed.",
      },
      { question: "Day-of-week 0 vs 7?",
        answer: "Many systems treat 0 and 7 as Sunday; confirm your scheduler’s convention.",
      },
      { question: "Timezone?",
        answer: "Cron entries are usually interpreted in the server’s local or configured zone; not inferred here.",
      },
    ],
    related: ["unix-timestamp-converter", "uuid-generator", "sql-formatter", "jwt-decoder", "json-validator"],
  },
  {
    slug: "markdown-to-html-converter",
    name: "Markdown to HTML (Core Syntax)",
    shortDescription: "Convert headings, lists, bold, italics, links, and code blocks to HTML.",
    description:
      "Client-side converter for a practical Markdown subset: ATX headings, lists, emphasis, links, inline code, and fenced code blocks. Output is meant for drafts; sanitize before rendering untrusted Markdown on a site.",
    category: "developer",
    fields: [{ name: "md", label: "Markdown", type: "textarea", placeholder: "# Title\n\n**bold** and [link](https://example.com)" }],
    keywords: ["markdown to html", "md to html converter online", "markdown preview html", "convert md to html", "markdown converter developer"],
    howToUse: ["Paste Markdown.", "Click Calculate to emit HTML.", "Copy into CMS, static generators, or email templates after your own sanitization policy."],
    faqs: [
      { question: "Is every Markdown extension supported?",
        answer: "No; tables, footnotes, and GitHub-only extensions may not render; use a full processor for those.",
      },
      { question: "Is the HTML safe to paste into a blog?",
        answer: "Run through your platform sanitizer; Markdown can include raw HTML in advanced cases.",
      },
      { question: "Does it support fenced code blocks?",
        answer: "Yes; triple backtick fences map to <pre><code> with basic escaping inside.",
      },
      { question: "Can I convert HTML back to Markdown?",
        answer: "Use a dedicated round-trip tool; this page is Markdown → HTML only.",
      },
      { question: "Performance on large files?",
        answer: "Very large documents may be slow in-browser; split chapters when possible.",
      },
    ],
    related: ["json-formatter", "html-to-json-converter", "json-to-html-converter", "sql-formatter", "regex-tester"],
  },
  {
    slug: "unix-timestamp-converter",
    name: "Unix Timestamp Converter",
    shortDescription: "Convert epoch seconds ↔ ISO 8601 in UTC.",
    description:
      "Translate Unix epoch seconds to UTC ISO timestamps and back. Clarifies millisecond inputs by normalizing length. Ideal for logs, JWT iat/exp checks, and API debugging.",
    category: "developer",
    fields: [
      {
        name: "mode",
        label: "Direction",
        type: "select",
        options: [
          { label: "Epoch seconds → UTC ISO", value: "epoch_to_iso" },
          { label: "ISO / datetime → Epoch seconds", value: "iso_to_epoch" },
        ],
      },
      { name: "input", label: "Value", type: "textarea", placeholder: "1735689600 or 2025-01-01T00:00:00Z" },
    ],
    keywords: ["unix timestamp converter", "epoch to date online", "iso 8601 to unix", "utc timestamp tool", "milliseconds epoch converter"],
    howToUse: ["Pick conversion direction.", "Paste epoch seconds (digits) or an ISO-like UTC string.", "Click Calculate for normalized output and a GMT line."],
    faqs: [
      { question: "Milliseconds vs seconds?",
        answer: "13-digit values are treated as milliseconds and divided by 1000 for standard Unix seconds.",
      },
      { question: "Which timezone is used?",
        answer: "Outputs emphasize UTC; local wall-clock conversion is left to your environment.",
      },
      { question: "Why did ISO parsing fail?",
        answer: "Strings must be parseable by JavaScript Date; include timezone (Z or offset) when ambiguous.",
      },
      { question: "Leap seconds?",
        answer: "JavaScript Date maps POSIX-like behavior; do not use this for legal leap-second litigation precision.",
      },
      { question: "Negative epochs?",
        answer: "Negative values represent times before 1970 when parsed as numeric epoch seconds.",
      },
    ],
    related: ["jwt-decoder", "json-validator", "regex-tester", "url-encoder-decoder", "api-response-formatter"],
  },
  {
    slug: "gst-calculator-australia",
    name: "GST Calculator Australia (10%)",
    shortDescription: "Add or remove 10% Australian GST on amounts.",
    description:
      "Model Australian Goods and Services Tax at 10%: start from GST-exclusive to get GST and GST-inclusive totals, or start GST-inclusive to back out net and GST. Educational; not tax advice; confirm with your accountant and ATO guidance.",
    category: "finance",
    fields: [
      { name: "amount", label: "Amount (AUD)", type: "number", min: 0, step: 0.01 },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        options: [
          { label: "GST-exclusive → add GST", value: "exclusive" },
          { label: "GST-inclusive → remove GST", value: "inclusive" },
        ],
      },
    ],
    keywords: ["gst calculator australia", "remove gst from amount australia", "add gst 10 percent", "gst inclusive exclusive calculator", "ato gst calculation helper"],
    howToUse: [
      "Enter the dollar amount in AUD.",
      "Choose whether your input is GST-exclusive or GST-inclusive.",
      "Click Calculate to see net, GST component, and gross.",
      "Cross-check invoices and rounding rules used by your billing system.",
    ],
    faqs: [
      { question: "Is the rate always 10%?",
        answer: "Standard GST is 10% for many supplies; some items are GST-free or input-taxed; this tool does not classify supplies.",
      },
      { question: "Rounding differences vs Xero/MYOB?",
        answer: "Per-line vs invoice-total rounding can differ by a few cents; mirror your accounting policy.",
      },
      { question: "Does this include BAS lodgment rules?",
        answer: "No; it is arithmetic only for quick checks.",
      },
      { question: "Can I use non-AUD currencies?",
        answer: "Math is the same but GST law context is Australia-specific; label currency clearly.",
      },
      { question: "Is this official ATO advice?",
        answer: "No. Use ATO materials and professionals for compliance decisions.",
      },
    ],
    related: ["vat-calculator", "invoice-late-fee-calculator", "profit-margin-calculator-business", "freelance-day-rate-calculator", "break-even-calculator"],
  },
  {
    slug: "zakat-calculator",
    name: "Zakat Calculator (2.5% above Nisab)",
    shortDescription: "Estimate Zakat due when zakatable wealth exceeds your chosen nisab threshold.",
    description:
      "Compute 2.5% on wealth above a nisab threshold you supply (gold/silver equivalents change; consult your scholar or institution). This is educational only and not a religious ruling.",
    category: "finance",
    fields: [
      { name: "wealth", label: "Total zakatable wealth (same currency)", type: "number", min: 0, step: 0.01 },
      { name: "nisab", label: "Nisab threshold amount", type: "number", min: 0, step: 0.01 },
      { name: "rate", label: "Zakat rate (%)", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["zakat calculator", "calculate zakat on savings", "nisab zakat amount", "2.5 percent zakat calculator", "gold silver nisab zakat tool"],
    howToUse: [
      "Sum eligible assets the same way your school of thought prescribes.",
      "Enter the nisab threshold you are using for the lunar year (from bullion prices or scholar tables).",
      "Keep rate at 2.5 unless your scenario explicitly differs.",
      "Click Calculate for an indicative due amount when wealth exceeds nisab.",
    ],
    faqs: [
      { question: "Who sets nisab?",
        answer: "Traditionally tied to gold/silver weights; amounts move with market prices; you must supply the threshold you follow.",
      },
      { question: "Does this include business inventory and receivables?",
        answer: "You should model those externally; the tool multiplies surplus above nisab by your rate only.",
      },
      { question: "Is this a fatwa?",
        answer: "No; it is arithmetic assistance only.",
      },
      { question: "Multiple currencies?",
        answer: "Convert everything to one currency first for a consistent surplus line.",
      },
      { question: "Debts deductible?",
        answer: "Deduct qualifying debts per your guidance before entering zakatable wealth.",
      },
    ],
    related: ["gst-calculator-australia", "net-worth-calculator", "emergency-fund-calculator", "invoice-late-fee-calculator", "currency-converter"],
  },
  {
    slug: "freelance-day-rate-calculator",
    name: "Freelance Day Rate Calculator",
    shortDescription: "Turn annual income targets and billable days into a minimum day rate.",
    description:
      "Divide after-tax income goals across realistic billable days per year to estimate a floor day rate before discounts. Complements hourly models; still not legal or tax advice.",
    category: "business",
    fields: [
      { name: "annualTarget", label: "Annual after-tax income target", type: "number", min: 0, step: 0.01 },
      { name: "billableDays", label: "Billable days per year", type: "number", min: 1, step: 1 },
      { name: "taxRate", label: "Tax + reserve margin (%)", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["freelance day rate calculator", "consulting day rate from annual goal", "contractor daily rate calculator", "billable days rate", "freelancer pricing day rate"],
    howToUse: [
      "Enter the annual income you want to keep after tax.",
      "Estimate realistic billable days (exclude holidays, admin, sales).",
      "Add a tax/reserve margin percent to gross-up the requirement.",
      "Click Calculate for a floor day rate before discounts and scope creep buffers.",
    ],
    faqs: [
      { question: "How is this different from the hourly freelance rate tool?",
        answer: "This page focuses on day = annual goal ÷ billable days with a gross-up margin; the hourly tool amortizes hours differently.",
      },
      { question: "Should I add overhead?",
        answer: "Increase annual target to reflect software, insurance, and subcontractor costs before dividing.",
      },
      { question: "What about partial days?",
        answer: "Translate to hours internally: day rate ÷ typical hours per day.",
      },
      { question: "Does this include VAT/GST quoting?",
        answer: "No; layer taxes on top per market after you compute a professional fee baseline.",
      },
      { question: "Is this negotiation advice?",
        answer: "No; it is a planning number to compare against market comps.",
      },
    ],
    related: ["freelance-rate-calculator", "employee-cost-calculator", "invoice-late-fee-calculator", "break-even-calculator", "profit-margin-calculator"],
  },
  {
    slug: "employee-cost-calculator",
    name: "Employee Loaded Cost Calculator",
    shortDescription: "Estimate total employer cost from salary, benefits, and overhead load.",
    description:
      "Combine base salary with employer-side benefits percentage and an overhead multiplier (rent, IT, managers) to approximate loaded annual cost per employee seat.",
    category: "business",
    fields: [
      { name: "salary", label: "Base salary (annual)", type: "number", min: 0, step: 0.01 },
      { name: "benefitsPct", label: "Employer benefits + payroll taxes (%)", type: "number", min: 0, step: 0.01 },
      { name: "overheadPct", label: "Overhead allocation (%)", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["employee cost calculator", "loaded labor cost calculator", "employer cost of employee", "fully loaded salary calculator", "benefits overhead staffing cost"],
    howToUse: [
      "Enter annual base salary.",
      "Estimate employer-side benefits and payroll taxes as a percent of salary.",
      "Add overhead allocation for shared services.",
      "Click Calculate for an illustrative loaded annual cost.",
    ],
    faqs: [
      { question: "Does this include equity grants?",
        answer: "No; add those manually if you annualize RSU/option expense separately.",
      },
      { question: "Contractor vs employee?",
        answer: "Contractor day rates often embed their own overhead; do not double-count.",
      },
      { question: "Global payroll?",
        answer: "Percentages vary widely by country; plug the burden rate you already benchmarked.",
      },
      { question: "Part-time employees?",
        answer: "Use pro-rated salary first, then apply percentages.",
      },
      { question: "Is this GAAP accurate?",
        answer: "No; it is directional for staffing and pricing models.",
      },
    ],
    related: ["freelance-day-rate-calculator", "meeting-cost-calculator", "break-even-calculator-business", "profit-margin-calculator-business", "roi-calculator"],
  },
  {
    slug: "invoice-late-fee-calculator",
    name: "Invoice Late Fee Calculator (Simple Interest)",
    shortDescription: "Estimate late fees from principal, days overdue, and annual rate.",
    description:
      "Apply a simple-interest style late fee: principal × (annual rate) × (days ÷ 365). Useful for contract drafts; statutes may cap rates; this is not legal advice.",
    category: "business",
    fields: [
      { name: "principal", label: "Outstanding invoice amount", type: "number", min: 0, step: 0.01 },
      { name: "daysLate", label: "Days late", type: "number", min: 0, step: 1 },
      { name: "annualRate", label: "Contractual annual rate (%)", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["invoice late fee calculator", "overdue interest calculator", "simple interest late payment fee", "accounts receivable late fee", "contract late fee estimate"],
    howToUse: ["Enter unpaid principal.", "Enter whole days late since clear due date.", "Enter the annual percentage allowed in your agreement.", "Click Calculate for fee and total due snapshot."],
    faqs: [
      { question: "Compound interest?",
        answer: "This version uses simple interest for transparency; compound policies need a different model.",
      },
      { question: "Usury caps?",
        answer: "Many jurisdictions cap consumer or commercial late rates; validate legally.",
      },
      { question: "360 vs 365 day count?",
        answer: "This tool uses 365-day year basis unless you adjust the rate manually for bank conventions.",
      },
      { question: "Partial payments?",
        answer: "Reduce principal first before late window in real accounting; this single-principal line is illustrative.",
      },
      { question: "Currency?",
        answer: "Unitless; keep one currency throughout.",
      },
    ],
    related: ["gst-calculator-australia", "vat-calculator", "profit-margin-calculator-business", "freelance-day-rate-calculator", "discount-calculator"],
  },
  {
    slug: "stone-to-kg-converter",
    name: "Stone to KG Converter",
    shortDescription: "Convert stone (st) to kilograms and reverse.",
    description:
      "Convert imperial stone to metric kilograms using the standard definition 1 stone = 14 pounds = 6.35029318 kg. Supports decimal stone for precision.",
    category: "converters",
    fields: [
      {
        name: "direction",
        label: "Direction",
        type: "select",
        options: [
          { label: "Stone → Kilograms", value: "st_to_kg" },
          { label: "Kilograms → Stone", value: "kg_to_st" },
        ],
      },
      { name: "value", label: "Amount to convert", type: "number", min: 0, step: 0.0001 },
    ],
    keywords: ["stone to kg converter", "kg to stone calculator", "convert st to kilograms", "body weight stone kg", "14 pounds in stone conversion"],
    howToUse: ["Pick conversion direction.", "Enter a non-negative numeric amount.", "Click Calculate for the converted value with high precision.", "Round for display per your locale norms."],
    faqs: [
      { question: "How many kg in one stone?",
        answer: "Exactly 6.35029318 kg by international agreement (via 14 lb at 0.45359237 kg/lb).",
      },
      { question: "Fractional stone?",
        answer: "Decimal stone is accepted (e.g., 12.5 st).",
      },
      { question: "Why differs from gym scale?",
        answer: "Rounding and clothing differences; this is pure unit math.",
      },
      { question: "UK vs US stone?",
        answer: "Stone is primarily UK/Ireland usage; the conversion factor is the same.",
      },
      { question: "Pounds field?",
        answer: "Combine pounds with stone manually (st + lb/14) before converting if needed.",
      },
    ],
    related: ["kg-to-lbs", "feet-inches-to-cm-converter", "acres-to-hectares-converter", "cm-to-feet", "celsius-to-fahrenheit"],
  },
  {
    slug: "feet-inches-to-cm-converter",
    name: "Feet & Inches to CM Converter",
    shortDescription: "Convert ft/in to centimeters and reverse with inch precision.",
    description:
      "Height-style conversion: combine feet and whole inches to centimeters, or convert centimeters back to feet and fractional inches for display.",
    category: "converters",
    fields: [
      {
        name: "direction",
        label: "Direction",
        type: "select",
        options: [
          { label: "Feet + inches → Centimeters", value: "ftin_to_cm" },
          { label: "Centimeters → Feet + inches", value: "cm_to_ftin" },
        ],
      },
      { name: "feet", label: "Feet (use 0 when converting from cm only)", type: "number", min: 0, step: 1 },
      { name: "inches", label: "Inches (0–11 typical when paired with feet)", type: "number", min: 0, step: 0.01 },
      { name: "cm", label: "Centimeters (cm→ft/in mode)", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["feet inches to cm", "height converter feet to cm", "cm to feet and inches", "ft in cm calculator", "imperial height to metric"],
    howToUse: [
      "Choose direction.",
      "For ft/in → cm: enter feet and inches (typically inches < 12).",
      "For cm → ft/in: enter centimeters; feet/inches fields are ignored.",
      "Click Calculate and copy results for forms or medical charts as permitted.",
    ],
    faqs: [
      { question: "Inches ≥ 12?",
        answer: "Normalize first (e.g., 5 ft 14 in → 6 ft 2 in) to avoid ambiguous displays.",
      },
      { question: "Decimal inches?",
        answer: "Supported for precision (e.g., 5 ft 10.5 in).",
      },
      { question: "Medical use?",
        answer: "This is math only; follow clinical rounding policies.",
      },
      { question: "Negative heights?",
        answer: "Not accepted; use positive magnitudes.",
      },
      { question: "cm only field ignored in ft/in mode?",
        answer: "Yes; only feet+inches are read when converting to centimeters.",
      },
    ],
    related: ["cm-to-feet", "stone-to-kg-converter", "kg-to-lbs", "acres-to-hectares-converter", "km-to-miles"],
  },
  {
    slug: "acres-to-hectares-converter",
    name: "Acres to Hectares Converter",
    shortDescription: "Convert acres ↔ hectares for land area.",
    description:
      "High-precision conversion between acres and hectares (1 acre = 0.40468564224 hectares). Useful for agriculture, rural property, and GIS back-of-envelope checks.",
    category: "converters",
    fields: [
      {
        name: "direction",
        label: "Direction",
        type: "select",
        options: [
          { label: "Acres → Hectares", value: "ac_to_ha" },
          { label: "Hectares → Acres", value: "ha_to_ac" },
        ],
      },
      { name: "value", label: "Area amount", type: "number", min: 0, step: 0.0000001 },
    ],
    keywords: ["acres to hectares converter", "hectares to acres", "convert acres ha", "farmland area converter", "land unit conversion acres"],
    howToUse: ["Select direction.", "Enter a non-negative area.", "Click Calculate for converted units with many decimals; round for display."],
    faqs: [
      { question: "US survey acres?",
        answer: "This uses international acre; survey acres differ slightly for legal parcels in some US states.",
      },
      { question: "Square meters?",
        answer: "1 ha = 10,000 m²; multiply after converting if needed.",
      },
      { question: "GPS polygons?",
        answer: "Use GIS tools for geodesic area; this is flat unit conversion only.",
      },
      { question: "Why so many decimals?",
        answer: "Preserves precision for chaining calculations; trim in prose.",
      },
      { question: "UK vs US acre?",
        answer: "International acre is used here for both.",
      },
    ],
    related: ["stone-to-kg-converter", "feet-inches-to-cm-converter", "km-to-miles", "fuel-efficiency-calculator", "cm-to-feet"],
  },
];
