import type { ToolDefinition } from "./types";

const q = (question: string, answer: string) => ({ question, answer });

/**
 * Phase 2 expansion: developer text utilities, UK finance sketches, marketplace fees, ops metrics, converters.
 * Compute lives in `expansion-phase2-compute.ts`; SEO profiles in `phase2-seo-expansion-batch2.ts`.
 */
export const expansionPhase2ToolDefinitions: ToolDefinition[] = [
  {
    slug: "html-formatter",
    name: "HTML Formatter",
    shortDescription: "Pretty-print HTML by splitting tags onto new lines.",
    description:
      "Improve readability of HTML snippets by inserting line breaks between tags. Best for logs, templates, and quick reviews; it does not validate full documents or auto-close tags.",
    category: "developer",
    fields: [{ name: "html", label: "HTML", type: "textarea", placeholder: "<div><p>Hello</p></div>" }],
    keywords: ["html formatter online", "pretty print html", "format html tags", "beautify html snippet", "html readability tool"],
    howToUse: [
      "Paste HTML from templates, CMS exports, or email sources.",
      "Click Calculate to insert breaks between adjacent tags.",
      "Re-indent inside large script or style blocks manually if needed.",
      "Sanitize before rendering user-supplied HTML on a public site.",
    ],
    faqs: [
      q("Does this validate HTML5?", "No; it is a whitespace/readability helper only."),
      q("Will it break inline SVG or large JSON in attributes?", "Very long single-line nodes stay long; split carefully in an editor if needed."),
      q("Does it send HTML to a server?", "No; processing stays in your browser session."),
      q("Can it format JSX?", "JSX often needs a dedicated formatter; results here are best-effort."),
      q("Is the output safe to paste into WordPress?", "Strip dangerous tags per your CMS policy first."),
    ],
    related: ["markdown-to-html-converter", "json-formatter", "xml-formatter", "css-minifier", "api-response-formatter"],
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    shortDescription: "Shrink CSS by removing comments and extra whitespace.",
    description:
      "Produce a tighter CSS string for faster payloads by stripping block comments and collapsing whitespace. Keep an unminified source file; this output is meant for deployment artifacts.",
    category: "developer",
    fields: [{ name: "css", label: "CSS", type: "textarea", placeholder: "/* reset */\nbody { color: #111; }\n" }],
    keywords: ["css minifier online", "minify css free", "compress css", "remove css comments", "css bundle shrinker"],
    howToUse: [
      "Paste CSS (single file or concatenated bundle).",
      "Click Calculate for a one-line style payload sketch.",
      "Diff against source before shipping; some comments document breakpoints.",
      "Pair with HTTP caching headers on your CDN.",
    ],
    faqs: [
      q("Does it rename classes?", "No; only whitespace and comments are touched in this pass."),
      q("What about `calc()` spaces?", "Aggressive collapse may tighten some expressions; verify in browser devtools."),
      q("Source maps?", "Not generated here; use your build tool for production source maps."),
      q("SCSS or LESS?", "Compile to CSS first, then minify."),
      q("Legal comment headers?", "They will be removed; re-append licenses in your pipeline if required."),
    ],
    related: ["html-formatter", "json-minifier", "markdown-to-html-converter", "api-response-formatter", "color-palette-generator"],
  },
  {
    slug: "json-minifier",
    name: "JSON Minifier",
    shortDescription: "Remove whitespace from JSON for compact wire formats.",
    description:
      "Parse JSON and emit a single-line minified string ideal for APIs, cache keys, and configuration blobs. Invalid JSON returns a clear syntax error.",
    category: "developer",
    fields: [{ name: "json", label: "JSON", type: "textarea", placeholder: '{ "a": 1, "b": [2, 3] }' }],
    keywords: ["json minifier online", "minify json", "compress json string", "json one line", "json minify browser"],
    howToUse: ["Paste JSON.", "Click Calculate.", "Copy the compact line into requests or env files.", "Validate upstream schemas separately."],
    faqs: [
      q("Does order of keys change?", "Object key order follows the parser; do not rely on ordering for semantics."),
      q("Large files?", "Very large JSON may slow the tab; split payloads when possible."),
      q("Pretty print?", "Use the existing JSON formatter tool for indented output."),
      q("JSON with comments?", "Not supported; strip comments first."),
      q("Unicode escapes?", "They round-trip through JSON.parse/stringify rules."),
    ],
    related: ["json-formatter", "json-validator", "csv-to-json-converter", "yaml-validator", "jwt-decoder"],
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    shortDescription: "Split XML tags onto separate lines for easier reading.",
    description:
      "Improve readability of XML responses, SOAP envelopes, and Android resources by breaking between tags. Does not validate against XSD or perform entity expansion.",
    category: "developer",
    fields: [{ name: "xml", label: "XML", type: "textarea", placeholder: "<root><item id='1'/></root>" }],
    keywords: ["xml formatter online", "pretty print xml", "format xml string", "xml readability", "soap xml viewer"],
    howToUse: ["Paste XML.", "Click Calculate.", "Review namespaces and xsi attributes manually.", "Validate with your schema tool before production writes."],
    faqs: [
      q("Does it indent hierarchically?", "This pass focuses on tag line breaks; deep indenting may still need an IDE."),
      q("CDATA sections?", "Left intact as single blocks when no inner `><` splits exist."),
      q("Huge responses?", "Consider streaming parsers server-side for multi-megabyte XML."),
      q("Security?", "Never paste secret keys into shared machines."),
      q("HTML vs XML?", "HTML is looser; use the HTML formatter for mixed documents."),
    ],
    related: ["html-formatter", "json-formatter", "csv-to-json-converter", "yaml-validator", "api-response-formatter"],
  },
  {
    slug: "yaml-validator",
    name: "YAML Validator",
    shortDescription: "Check YAML syntax and show the parsed root type.",
    description:
      "Parse YAML in-browser to catch indentation mistakes and bad anchors before CI. Reports whether the document is a map, sequence, or scalar at the root; not a Kubernetes schema validator.",
    category: "developer",
    fields: [{ name: "yaml", label: "YAML", type: "textarea", placeholder: "service:\n  port: 8080\n" }],
    keywords: ["yaml validator online", "check yaml syntax", "kubernetes yaml lint basic", "yaml parse error", "validate yaml free"],
    howToUse: ["Paste docker-compose, GitHub Actions, or Helm values snippets.", "Click Calculate.", "Fix line/column errors the parser reports.", "Run kubeconform or schema tests in CI for cluster safety."],
    faqs: [
      q("Does this validate Kubernetes resources?", "Syntax only; schema validation belongs in kubectl/kubeconform."),
      q("Multiple documents with `---`?", "Supported when the parser accepts the stream."),
      q("Tabs vs spaces?", "YAML forbids tabs for indentation in many parsers; prefer spaces."),
      q("Secrets in YAML?", "Avoid pasting production secrets on shared devices."),
      q("JSON compatibility?", "JSON is valid YAML 1.2; you can paste JSON here too."),
    ],
    related: ["json-validator", "json-formatter", "csv-to-json-converter", "markdown-to-html-converter", "regex-tester"],
  },
  {
    slug: "csv-to-json-converter",
    name: "CSV to JSON Converter",
    shortDescription: "Turn header + rows CSV into an array of JSON objects.",
    description:
      "Convert simple spreadsheets to JSON for APIs and fixtures. Assumes the first row is headers; quoted fields may contain commas. Empty lines are skipped.",
    category: "developer",
    fields: [{ name: "csv", label: "CSV", type: "textarea", placeholder: "name,score\nAda,99\nBob,87" }],
    keywords: ["csv to json online", "convert csv to json", "spreadsheet to json", "csv parser browser", "export csv json array"],
    howToUse: ["Export CSV from Excel or Sheets with a header row.", "Paste into the text area.", "Click Calculate for JSON array output.", "Cast numbers in your app if types matter."],
    faqs: [
      q("Semicolon-separated?", "Not supported; convert delimiters to commas first."),
      q("Merged cells?", "Flatten them in the spreadsheet before export."),
      q("UTF-8 BOM?", "Strip BOM in editor if the first header looks wrong."),
      q("Nested JSON?", "This tool emits flat objects per row; model trees in code."),
      q("Huge files?", "Browser memory limits apply; chunk large datasets."),
    ],
    related: ["json-formatter", "json-validator", "yaml-validator", "sql-formatter", "api-response-formatter"],
  },
  {
    slug: "jwt-expiry-checker",
    name: "JWT Expiry Checker",
    shortDescription: "Read exp/iat from a JWT and compare to current time.",
    description:
      "Decode the payload segment of a JWT without verifying signatures, then interpret exp and iat in UTC. Useful when debugging session timeouts; never treat output as proof of authenticity.",
    category: "developer",
    fields: [{ name: "jwt", label: "JWT", type: "textarea", placeholder: "eyJhbGciOiJIUzI1NiJ9..." }],
    keywords: ["jwt expiry checker", "check jwt expiration online", "jwt exp time remaining", "decode jwt exp", "jwt ttl viewer"],
    howToUse: ["Paste a three-part JWT.", "Click Calculate.", "Read exp relative to now.", "Verify signatures in your auth service before trusting claims."],
    faqs: [
      q("Clock skew?", "Compare server clocks; one minute skew can confuse support tickets."),
      q("Opaque refresh tokens?", "They are not JWT-shaped; use your IdP logs instead."),
      q("Milliseconds exp?", "Non-integer exp is unusual; numeric seconds are assumed."),
      q("Why not verify?", "Keys live on your servers; this page never sees them."),
      q("JWE tokens?", "Encrypted layouts are not supported here."),
    ],
    related: ["jwt-decoder", "unix-timestamp-converter", "json-validator", "api-status-checker", "regex-tester"],
  },
  {
    slug: "api-status-checker",
    name: "API URL Checker (curl helper)",
    shortDescription: "Validate endpoint URLs and copy a curl probe command.",
    description:
      "Sanity-check http(s) URLs and print a ready-to-run curl -I example. Live status codes are not fetched inside this synchronous calculator; use curl, Postman, or your uptime monitor for real HTTP results.",
    category: "developer",
    fields: [{ name: "url", label: "Endpoint URL", type: "text", placeholder: "https://api.example.com/health" }],
    keywords: ["api url validator", "check api endpoint format", "curl health check command", "http url syntax check", "rest endpoint tester helper"],
    howToUse: ["Paste a full URL including scheme.", "Click Calculate.", "Copy the suggested curl command into a terminal.", "Interpret status codes in your staging environment."],
    faqs: [
      q("Why not show HTTP 200 here?", "Network calls are async; Toollabz compute stays synchronous for reliability."),
      q("CORS errors in the browser?", "curl bypasses browser CORS; prefer it for APIs."),
      q("Self-signed TLS?", "curl needs -k only in trusted lab settings."),
      q("GraphQL POST bodies?", "Use curl -d with JSON headers from your API docs."),
      q("Rate limits?", "Space out probes so monitoring does not trip WAF rules."),
    ],
    related: ["api-response-formatter", "json-validator", "jwt-expiry-checker", "url-encoder-decoder", "regex-tester"],
  },
  {
    slug: "self-employed-tax-calculator-uk",
    name: "Self Employed Tax Calculator UK",
    shortDescription: "Sketch take-home profit after income tax and NI percentages.",
    description:
      "Multiply annual profit by effective income tax and National Insurance percentages you supply. HM Revenue rules, bands, dividends, and payments on account are not auto-modeled; use your accountant for filings.",
    category: "finance",
    fields: [
      { name: "annualProfit", label: "Annual profit (GBP)", type: "number", min: 0, step: 0.01 },
      { name: "incomeTaxPercent", label: "Effective income tax (%)", type: "number", min: 0, step: 0.01 },
      { name: "niPercent", label: "Effective NI (%)", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["self employed tax calculator uk", "sole trader take home calculator uk", "freelancer tax estimate uk", "self assessment profit tax sketch", "uk ni and tax percentage model"],
    howToUse: [
      "Estimate annual taxable profit after allowable expenses.",
      "Enter effective income tax % from your forecast.",
      "Enter effective NI % (Class 2/4 sketch).",
      "Click Calculate for illustrative take-home cash.",
    ],
    faqs: [
      q("Is this HMRC software?", "No; it is arithmetic on percentages you choose."),
      q("Payments on account?", "Not modeled; adjust cash timing in your spreadsheet."),
      q("Limited company vs sole trader?", "This flow targets sole trader style profit inputs."),
      q("Dividends?", "Use the dividend calculator for distribution tax sketches."),
      q("Scottish rates?", "Enter the effective % that reflects your banding."),
    ],
    related: ["dividend-tax-calculator-uk", "salary-after-tax-calculator-uk", "freelance-day-rate-calculator", "invoice-late-fee-calculator", "gst-calculator-australia"],
  },
  {
    slug: "dividend-tax-calculator-uk",
    name: "Dividend Tax Calculator UK",
    shortDescription: "Estimate net dividends after an effective dividend tax rate.",
    description:
      "Apply a single dividend tax percentage to gross dividends for planning decks. The UK dividend allowance and income tax bands are not auto-applied; supply an effective rate from your tax forecast.",
    category: "finance",
    fields: [
      { name: "dividendGross", label: "Gross dividends (GBP)", type: "number", min: 0, step: 0.01 },
      { name: "dividendTaxPercent", label: "Effective dividend tax (%)", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["dividend tax calculator uk", "uk dividend tax estimate", "net dividend calculator", "dividend allowance planning", "director dividend tax sketch"],
    howToUse: ["Enter gross dividends voted or projected.", "Enter effective tax % after allowances.", "Click Calculate for net cash hint.", "Reconcile with accountant before distributions."],
    faqs: [
      q("Where is the £500 / £1,000 allowance?", "Fold allowances into the effective % you type."),
      q("Different rates for basic/higher?", "Model slices externally or blend into one %."),
      q("IR35 considerations?", "Outside scope; separate employment income tools."),
      q("ISA dividends?", "Usually tax-free; do not enter those here."),
      q("Currency?", "Labels assume GBP for UK context."),
    ],
    related: ["self-employed-tax-calculator-uk", "salary-after-tax-calculator-uk", "profit-margin-calculator-business", "roi-calculator", "net-worth-calculator"],
  },
  {
    slug: "stripe-fee-calculator",
    name: "Stripe Fee Calculator",
    shortDescription: "Estimate Stripe processing fees with percent + fixed components.",
    description:
      "Combine percentage and fixed per-transaction fees on a charge amount. International cards, currency conversion, Radar, Billing, and tax on fees are not auto-included; tune inputs to match your Stripe dashboard exports.",
    category: "finance",
    fields: [
      { name: "chargeAmount", label: "Charge amount", type: "number", min: 0, step: 0.01 },
      { name: "feePercent", label: "Card fee (%)", type: "number", min: 0, step: 0.01 },
      { name: "fixedFee", label: "Fixed fee per charge", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["stripe fee calculator", "stripe processing fee estimate", "stripe domestic card fee", "online payment fee calculator", "stripe net payout calculator"],
    howToUse: ["Enter the gross charge your customer pays.", "Enter the blended % from your Stripe pricing page.", "Enter the fixed fee per authorization.", "Click Calculate for fee and net retained."],
    faqs: [
      q("Does this include VAT on fees?", "EU/UK VAT on Stripe fees is not modeled; adjust manually."),
      q("ACH vs cards?", "ACH has different tables; swap the % and fixed inputs."),
      q("Refunds?", "Stripe refund fees differ; this is for captured charges only."),
      q("Marketplace connect?", "Platform take rates are outside this single-party model."),
      q("Crypto or Link?", "Use the % that matches the tender type in your dashboard."),
    ],
    related: ["paypal-fee-calculator", "etsy-fee-calculator", "ebay-fee-calculator", "invoice-late-fee-calculator", "roi-calculator-marketing"],
  },
  {
    slug: "paypal-fee-calculator",
    name: "PayPal Fee Calculator",
    shortDescription: "Estimate PayPal fees with percent + fixed per transaction.",
    description:
      "Model domestic-style goods and services fees using editable percentage and fixed components. Micropayments, friends & family, chargebacks, and cross-border tables are not enumerated; align inputs with your PayPal fee report.",
    category: "finance",
    fields: [
      { name: "saleAmount", label: "Sale amount", type: "number", min: 0, step: 0.01 },
      { name: "feePercent", label: "PayPal fee (%)", type: "number", min: 0, step: 0.01 },
      { name: "fixedFee", label: "Fixed fee", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["paypal fee calculator", "paypal goods and services fee", "paypal seller fee estimate", "paypal percentage plus fixed", "paypal net after fees"],
    howToUse: ["Enter the payment amount.", "Enter the % from your PayPal commercial profile.", "Enter fixed fee per capture.", "Click Calculate for net proceeds."],
    faqs: [
      q("Friends & family?", "Usually no fee; this model targets goods/services."),
      q("Currency conversion?", "Add FX margin manually to the % if needed."),
      q("Chargeback fees?", "Not included; reserve risk separately."),
      q("Invoicing product?", "Fees can differ; mirror the invoice line."),
      q("UK vs US accounts?", "Use the numbers from your own fee schedule."),
    ],
    related: ["stripe-fee-calculator", "ebay-fee-calculator", "etsy-fee-calculator", "unit-price-calculator", "discount-calculator"],
  },
  {
    slug: "etsy-fee-calculator",
    name: "Etsy Fee Calculator",
    shortDescription: "Sketch Etsy-style listing, transaction, and payment fees.",
    description:
      "Sum a listing fee plus percentage transaction and payment processing fees on item price. Regulatory, advertising, and offsite ad fees are not auto-modeled; adjust percents to match your Etsy bill.",
    category: "finance",
    fields: [
      { name: "salePrice", label: "Item price", type: "number", min: 0, step: 0.01 },
      { name: "listingFee", label: "Listing fee (flat)", type: "number", min: 0, step: 0.01 },
      { name: "transactionPercent", label: "Transaction fee (%)", type: "number", min: 0, step: 0.01 },
      { name: "paymentPercent", label: "Payment processing (%)", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["etsy fee calculator", "etsy seller fees estimate", "etsy transaction fee calculator", "etsy payment processing fee", "etsy net profit calculator"],
    howToUse: ["Enter the customer-facing item price.", "Enter listing fee per renewal if applicable.", "Enter Etsy transaction % from your statement.", "Enter payment processing % and run Calculate."],
    faqs: [
      q("Offsite ads?", "Add an extra percent if you are in the mandatory ads program."),
      q("VAT on fees?", "Not auto-calculated; fold into percentages if needed."),
      q("Shipping labels?", "Exclude shipping label purchases here; model them separately."),
      q("Multi-quantity orders?", "Multiply price or run per-unit rows."),
      q("Currency settlement?", "Use the currency of your Etsy deposit for consistency."),
    ],
    related: ["ebay-fee-calculator", "stripe-fee-calculator", "paypal-fee-calculator", "profit-margin-calculator-business", "unit-price-calculator"],
  },
  {
    slug: "ebay-fee-calculator",
    name: "eBay Fee Calculator",
    shortDescription: "Estimate final value percent plus fixed order fees.",
    description:
      "Combine a final value percentage and per-order fixed fee on sold price. Promoted listings, managed payments FX spreads, and category-specific caps are not modeled; tune percents from your monthly fee CSV.",
    category: "finance",
    fields: [
      { name: "soldPrice", label: "Sold price", type: "number", min: 0, step: 0.01 },
      { name: "finalValuePercent", label: "Final value fee (%)", type: "number", min: 0, step: 0.01 },
      { name: "fixedPerOrder", label: "Fixed order fee", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["ebay fee calculator", "ebay final value fee calculator", "ebay seller fees estimate", "ebay net after fees", "ebay managed payments fee model"],
    howToUse: ["Enter the sold price including shipping if your category charges FVF on shipping.", "Enter the final value % from eBay charts.", "Enter fixed per-order fees.", "Click Calculate."],
    faqs: [
      q("Promoted listings?", "Add ad spend separately or increase the %."),
      q("Insertion fees?", "Add another fixed line manually."),
      q("Vehicle categories?", "Flat fees differ; override inputs."),
      q("Refunds?", "FVF credits have timing rules; not modeled."),
      q("Store subscription discounts?", "Lower the % to reflect your negotiated tier."),
    ],
    related: ["etsy-fee-calculator", "stripe-fee-calculator", "paypal-fee-calculator", "roi-calculator-marketing", "profit-margin-calculator-business"],
  },
  {
    slug: "churn-calculator",
    name: "Churn Calculator",
    shortDescription: "Project remaining customers under compound monthly churn.",
    description:
      "Apply a constant monthly churn percentage across a horizon to see how many customers remain. Useful for SaaS classroom models; real businesses use cohort retention and expansion revenue.",
    category: "business",
    fields: [
      { name: "startingCustomers", label: "Starting customers", type: "number", min: 0, step: 1 },
      { name: "monthlyChurnPercent", label: "Monthly churn (%)", type: "number", min: 0, step: 0.01 },
      { name: "months", label: "Months", type: "number", min: 0, step: 1 },
    ],
    keywords: ["churn calculator", "customer churn projection", "saas churn model simple", "monthly churn remaining customers", "logo churn calculator"],
    howToUse: ["Enter starting active customers.", "Enter monthly churn % from product analytics.", "Enter horizon in months.", "Click Calculate for remaining logos."],
    faqs: [
      q("Is this revenue churn?", "No; it models customer counts unless you assume one seat each."),
      q("Annual churn?", "Convert to monthly or multiply the horizon accordingly."),
      q("Negative churn?", "Use your BI tool; this model assumes nonnegative churn %."),
      q("Cohort shapes?", "Real curves decay nonlinearly; this is exponential shorthand."),
      q("Expansion?", "Pair with NRR dashboards separately."),
    ],
    related: ["ltv-calculator-saas", "cac-calculator-saas", "roas-calculator", "break-even-calculator-business", "conversion-rate-calculator"],
  },
  {
    slug: "roas-calculator",
    name: "ROAS Calculator",
    shortDescription: "Return on ad spend from revenue and media spend.",
    description:
      "Divide attributed conversion revenue by ad spend for ROAS and show ROI% on spend. Useful for paid search, social, and affiliate programs when revenue attribution is already agreed.",
    category: "marketing",
    fields: [
      { name: "conversionRevenue", label: "Attributed revenue", type: "number", min: 0, step: 0.01 },
      { name: "adSpend", label: "Ad spend", type: "number", min: 0, step: 0.01 },
    ],
    keywords: ["roas calculator", "return on ad spend calculator", "ad spend revenue ratio", "marketing roas formula", "paid ads efficiency calculator"],
    howToUse: ["Enter revenue credited to the campaign window.", "Enter media cost including platform fees if desired.", "Click Calculate for ROAS multiple.", "Compare channels using the same attribution window."],
    faqs: [
      q("ROAS vs ROI?", "ROAS is revenue ÷ spend; ROI here is (revenue − spend) ÷ spend."),
      q("View-through conversions?", "Decide policy before typing revenue."),
      q("Blended ROAS?", "Sum channels in Excel first, then use totals here."),
      q("Margin-aware ROAS?", "Subtract COGS externally or use contribution margin fields elsewhere."),
      q("Zero revenue days?", "ROAS can be zero; that is still informative."),
    ],
    related: ["google-ads-roi-calculator", "roi-calculator-marketing", "cpc-calculator", "conversion-rate-calculator", "churn-calculator"],
  },
  {
    slug: "working-days-calculator-uk",
    name: "Working Days Calculator UK",
    shortDescription: "Count Mon–Fri weekdays between dates minus bank holidays you enter.",
    description:
      "Count weekdays on a UTC calendar axis between inclusive ISO dates, then subtract a bank-holiday adjustment you provide. Does not embed the UK bank holiday calendar; payroll teams should enter holiday counts per period.",
    category: "utility",
    fields: [
      { name: "startDate", label: "Start date (YYYY-MM-DD)", type: "text", placeholder: "2026-01-05" },
      { name: "endDate", label: "End date (YYYY-MM-DD)", type: "text", placeholder: "2026-01-30" },
      { name: "bankHolidayDays", label: "Bank holidays to subtract", type: "number", min: 0, step: 1 },
    ],
    keywords: ["working days calculator uk", "uk business days between dates", "weekdays count payroll uk", "subtract bank holidays working days", "hmrc style working day count"],
    howToUse: ["Pick inclusive start and end dates.", "Look up England/Wales/Scotland holidays for that span.", "Enter how many holidays fall on weekdays.", "Click Calculate."],
    faqs: [
      q("Does it know Easter moves?", "No; you supply the holiday count explicitly."),
      q("Part-time workers?", "This counts calendar weekdays; allocate FTE separately."),
      q("Timezone?", "Dates are interpreted as UTC midnight anchors for repeatability."),
      q("Inclusive ends?", "Both start and end dates count if they are weekdays."),
      q("Scotland-only holidays?", "Subtract only the holidays your contract observes."),
    ],
    related: ["business-days-calculator", "date-difference-calculator", "time-zone-converter", "notice-period-calculator", "salary-after-tax-calculator-uk"],
  },
  {
    slug: "business-days-calculator",
    name: "Business Days Calculator",
    shortDescription: "Count Monday–Friday days between two calendar dates.",
    description:
      "Count weekdays inclusively between ISO YYYY-MM-DD values using UTC anchors. Useful for SLA timers and shipping estimates; add regional holidays manually if they apply.",
    category: "utility",
    fields: [
      { name: "startDate", label: "Start date (YYYY-MM-DD)", type: "text", placeholder: "2026-03-01" },
      { name: "endDate", label: "End date (YYYY-MM-DD)", type: "text", placeholder: "2026-03-31" },
    ],
    keywords: ["business days calculator", "weekdays between two dates", "monday to friday day count", "sla business days estimate", "working days excluding weekends"],
    howToUse: ["Enter inclusive ISO dates.", "Click Calculate.", "Add known public holidays manually if SLAs exclude them.", "Align stakeholders on inclusive vs exclusive semantics."],
    faqs: [
      q("Inclusive vs exclusive?", "Both endpoints are inclusive weekdays in this tool."),
      q("US federal holidays?", "Subtract them manually or use a count from a calendar export."),
      q("Half days?", "Not supported; round to full days in policy."),
      q("Weekend work?", "This still excludes Sat/Sun from the weekday tally."),
      q("Leap seconds?", "Not relevant to day counting here."),
    ],
    related: ["working-days-calculator-uk", "date-difference-calculator", "time-zone-converter", "age-calculator", "notice-period-calculator"],
  },
  {
    slug: "random-team-generator",
    name: "Random Team Generator",
    shortDescription: "Shuffle names into balanced random teams.",
    description:
      "Split a pasted list of teammates into N balanced groups using an in-browser shuffle. Great for hackathons and stand-up rotations; re-run for a new draw.",
    category: "utility",
    fields: [
      { name: "names", label: "Names (comma or newline separated)", type: "textarea", placeholder: "Ada\nBob\nChen\nDana" },
      { name: "teamCount", label: "Number of teams", type: "number", min: 2, step: 1 },
    ],
    keywords: ["random team generator", "split names into random groups", "shuffle teams online", "hackathon team randomizer", "fair random group maker"],
    howToUse: ["Paste every participant name.", "Choose how many teams you need.", "Click Calculate.", "Screenshot results for async retros."],
    faqs: [
      q("Is it cryptographically fair?", "It uses Math.random; good for icebreakers, not lottery law."),
      q("Uneven sizes?", "Teams differ by at most one person when counts do not divide evenly."),
      q("Duplicate names?", "They are treated as separate roster entries."),
      q("Gender balance?", "Manually edit teams after the shuffle if needed."),
      q("Remote teams?", "Same process; paste Slack handles instead of names."),
    ],
    related: ["random-name-generator", "username-generator", "word-counter", "case-converter", "color-palette-generator"],
  },
  {
    slug: "lbs-to-kg-converter",
    name: "LBS to KG Converter",
    shortDescription: "Convert pounds to kilograms with exact factor.",
    description:
      "Multiply pounds by the international avoirdupois conversion factor 0.45359237 kg per lb. Symmetric with the existing kg-to-lbs tool for round-trip checks.",
    category: "converters",
    fields: [{ name: "lbs", label: "Pounds (lb)", type: "number", min: 0, step: 0.0001 }],
    keywords: ["lbs to kg converter", "pounds to kilograms online", "lb to kg exact", "weight converter lbs kg", "bodyweight lbs to kg"],
    howToUse: ["Enter pounds.", "Click Calculate.", "Copy kg for nutrition or shipping forms.", "Compare with kg-to-lbs for sanity."],
    faqs: [
      q("Stone?", "Use the stone converter for UK bodyweight mixes."),
      q("Ounces?", "Convert ounces to decimal pounds first."),
      q("Shipping DIM weight?", "Dimensional rules differ by carrier; this is mass only."),
      q("Precision?", "Six decimals shown; round for display per jurisdiction."),
      q("Negative weights?", "Not supported; enter non-negative mass."),
    ],
    related: ["kg-to-lbs", "stone-to-kg-converter", "cm-to-feet", "celsius-to-fahrenheit", "pace-calculator"],
  },
  {
    slug: "feet-to-cm-converter",
    name: "Feet to CM Converter",
    shortDescription: "Convert decimal feet to centimeters for height and CAD.",
    description:
      "Multiply decimal feet by 30.48 for centimeters. Complements the feet+inches converter when you already have engineering feet rather than feet/inch pairs.",
    category: "converters",
    fields: [{ name: "feet", label: "Feet (decimal)", type: "number", min: 0, step: 0.0001, placeholder: "5.75" }],
    keywords: ["feet to cm converter", "decimal feet to centimeters", "ft to cm calculator", "height feet to cm", "engineering feet to cm"],
    howToUse: ["Enter feet as a decimal (e.g., 5.75 for five feet nine inches).", "Click Calculate.", "Use cm in metric forms.", "Cross-check with feet-inches converter if needed."],
    faqs: [
      q("Feet and inches separately?", "Use the feet+inches to cm tool for that UX."),
      q("CM back to feet?", "Use cm-to-feet for the inverse single-axis conversion."),
      q("Survey feet?", "US survey foot differs slightly; this uses international foot."),
      q("CAD scale?", "Great for importing imperial drawings into metric templates."),
      q("Negative lengths?", "Not supported."),
    ],
    related: ["cm-to-feet", "feet-inches-to-cm-converter", "km-to-miles", "pace-calculator", "square-feet-to-square-meters-converter"],
  },
  {
    slug: "pace-calculator",
    name: "Pace Calculator",
    shortDescription: "Minutes per km from distance and elapsed time.",
    description:
      "Enter distance in kilometers or miles plus elapsed hours, minutes, and seconds to see pace per kilometer and average speed in km/h and mph. Useful for training logs and race planning.",
    category: "converters",
    fields: [
      { name: "distance", label: "Distance", type: "number", min: 0, step: 0.0001 },
      {
        name: "distanceUnit",
        label: "Distance unit",
        type: "select",
        options: [
          { label: "Kilometres", value: "km" },
          { label: "Miles", value: "mi" },
        ],
      },
      { name: "hours", label: "Hours", type: "number", min: 0, step: 1 },
      { name: "minutes", label: "Minutes", type: "number", min: 0, step: 1 },
      { name: "seconds", label: "Seconds", type: "number", min: 0, step: 1 },
    ],
    keywords: ["pace calculator", "minutes per km calculator", "running pace calculator", "race pace from time and distance", "average speed from run"],
    howToUse: ["Enter race distance and unit.", "Enter chip time components.", "Click Calculate.", "Log pace per km for training zones."],
    faqs: [
      q("Treadmill vs GPS?", "Distance input should match how you measured the effort."),
      q("Walk breaks?", "Elapsed time includes pauses; that lowers average speed."),
      q("Track 400 m repeats?", "Convert total meters to km first."),
      q("Heart zones?", "Pair pace with HR data in your sports watch export."),
      q("Metric vs imperial pace?", "Primary pace line is per km; mph shown for context."),
    ],
    related: ["mph-to-kmh-converter", "km-to-miles", "cm-to-feet", "fuel-efficiency-calculator", "daily-calorie-calculator"],
  },
  {
    slug: "mph-to-kmh-converter",
    name: "MPH to KMH Converter",
    shortDescription: "Convert miles per hour to kilometres per hour.",
    description:
      "Multiply mph by 1.609344 for exact km/h per international mile definition. Helpful for automotive specs, aviation gust readouts, and weather reports.",
    category: "converters",
    fields: [{ name: "mph", label: "Miles per hour", type: "number", min: 0, step: 0.0001 }],
    keywords: ["mph to kmh converter", "miles per hour to km per hour", "speed converter mph kmh", "wind speed mph to kmh", "car speed mph to kmh"],
    howToUse: ["Enter mph.", "Click Calculate.", "Use km/h for EU spec sheets.", "Compare with km-to-miles for distance analogs."],
    faqs: [
      q("Knots?", "Convert knots separately; nautical miles differ."),
      q("Mach number?", "Not supported; speed of sound varies with altitude."),
      q("Rounding for tickets?", "Follow local law; this shows four decimals."),
      q("Electric vehicles?", "Same conversion for displayed top speeds."),
      q("Negative speeds?", "Not supported; enter magnitude."),
    ],
    related: ["km-to-miles", "pace-calculator", "fuel-efficiency-calculator", "celsius-to-fahrenheit", "cm-to-feet"],
  },
  {
    slug: "square-feet-to-square-meters-converter",
    name: "Square Feet to Square Meters Converter",
    shortDescription: "Convert ft² to m² using the international foot definition.",
    description:
      "Multiply square feet by 0.09290304 for square metres. Useful for flooring, office leases, and international listings.",
    category: "converters",
    fields: [{ name: "squareFeet", label: "Square feet", type: "number", min: 0, step: 0.0001 }],
    keywords: ["square feet to square meters", "sq ft to sqm converter", "ft2 to m2 calculator", "floor area converter", "real estate sqft to sqm"],
    howToUse: ["Enter area in square feet.", "Click Calculate.", "Use m² in EU datasheets.", "Cross-check architectural drawings for gross vs net area."],
    faqs: [
      q("Survey square feet?", "US survey foot differs slightly; confirm title documents."),
      q("Acres?", "Use acres-to-hectares for large land parcels."),
      q("Circular rooms?", "Enter already-computed square footage."),
      q("Basement vs GLA?", "Gross living area rules vary; tool is unit math only."),
      q("Decimals?", "Six m² decimals help before rounding to listing rules."),
    ],
    related: ["acres-to-hectares-converter", "mulch-volume-calculator", "paint-calculator", "floor-tile-quantity-calculator", "cm-to-feet"],
  },
];
