import type { Phase1Profile } from "./phase1-seo";

/** Deep SEO profiles merged into `phase1Profiles` in `content.ts` for Phase 1 expansion tools. */
export const expansionPhase1Profiles: Record<string, Phase1Profile> = {
  "jwt-decoder": {
    audience: "backend and full-stack engineers debugging OAuth and session tokens",
    scenario: "inspecting alg, kid, exp, and custom claims without spinning up jwt.io in a blocked network",
    exampleInput: "Paste a three-part JWT from your staging IdP (header.alg RS256, payload.sub and exp in seconds)",
    exampleOutput: "Pretty header/payload JSON, exp translated to ISO UTC, with a clear banner that signatures were not verified",
    pitfall: "assuming decoded bytes prove authenticity without signature verification",
    interpretation: "treat output as diagnostics only and verify with your platform keys",
    relatedIntent: "pair with Unix timestamp converter when reading exp/iat quickly",
    faq: [
      { question: "Does decoding prove the token is valid?", answer: "No; anyone can forge unsigned bytes; only your verifier proves trust." },
      { question: "Why is my payload garbled?", answer: "Some tokens compress or encrypt payloads; this tool targets standard JWS JSON payloads." },
      { question: "Can I paste refresh tokens?", answer: "Avoid pasting long-lived secrets on shared machines even if processing is local." },
      {
        question: "How do I sanity-check exp during an incident?",
        answer:
          "Decode, read exp as epoch seconds, convert to UTC, then compare against your centralized clock and session policy. If skew is under a minute but users still bounce, look for revocation lists or shorter server-side TTLs.",
      },
      {
        question: "What if kid is present but I do not have the matching JWK yet?",
        answer:
          "kid is a hint for key rotation. Pull JWKS from the issuer URL in a trusted environment, then verify signatures there. This page never fetches remote keys automatically.",
      },
    ],
  },
  "uuid-generator": {
    audience: "engineers seeding databases, QA fixtures, and correlation IDs",
    scenario: "need several RFC4122 v4 UUIDs without installing CLI tools",
    exampleInput: "count=8, lowercase",
    exampleOutput: "eight lines of random UUIDv4 strings",
    pitfall: "assuming uniqueness guarantees across partitioned databases without a collision strategy",
    interpretation: "use DB constraints or ULIDs when global coordination matters",
    relatedIntent: "move to JWT decoder when correlating logs with auth traces",
    faq: [
      { question: "Are collisions impossible?", answer: "Practically rare for v4, but your schema should still enforce uniqueness." },
      { question: "Why cap at 50?", answer: "Keeps the browser responsive; run multiple batches if needed." },
      { question: "Does this log UUIDs server-side?", answer: "Generation happens client-side in the tool workspace." },
    ],
  },
  "sql-formatter": {
    audience: "data analysts and engineers cleaning queries before code review",
    scenario: "one-line SQL from ORM logs needs readable structure for Slack or tickets",
    exampleInput: "select id,name from users where active=1 order by name",
    exampleOutput: "keyword line breaks with light indentation",
    pitfall: "running auto-formatted vendor-specific SQL without re-validating",
    interpretation: "use as a readability pass, not a query optimizer",
    relatedIntent: "open JSON validator when the same incident mixes API payloads and SQL snippets",
    faq: [
      { question: "Will this fix syntax errors?", answer: "No; it only rearranges whitespace for common keywords." },
      { question: "Does it support stored procedures?", answer: "Complex procedural blocks may still need manual formatting." },
      {
        question: "What about long CTE chains?",
        answer: "Very deep nested WITH statements may need manual blank lines after each CTE so reviewers can scan bindings quickly.",
      },
      { question: "My CTE broke. Why?", answer: "Nested WITH clauses may need manual newline placement after automated passes." },
    ],
  },
  "cron-expression-generator": {
    audience: "SREs and developers translating schedules between crontab, Kubernetes, and Quartz",
    scenario: "double-checking a five-field string before committing infra-as-code",
    exampleInput: "15 2 * * SUN",
    exampleOutput: "field-by-field natural language hints",
    pitfall: "forgetting timezone context on the target host",
    interpretation: "treat summaries as documentation aids, not scheduler guarantees",
    relatedIntent: "use Unix timestamp tool when correlating cron fires with log lines",
    faq: [
      { question: "Does this validate Quartz six-field cron?", answer: "No; classic five-field Unix layout is assumed." },
      { question: "Are DST transitions handled?", answer: "Not here; your platform clock defines actual execution." },
      { question: "Macro strings like @daily?", answer: "Convert macros to numeric fields before using this helper." },
    ],
  },
  "markdown-to-html-converter": {
    audience: "technical writers and devs drafting snippets for CMS or static site generators",
    scenario: "quick HTML preview for README-style Markdown without opening an editor plugin",
    exampleInput: "# Title\n\n- item\n\n**bold**",
    exampleOutput: "escaped HTML with headings, list, and strong tags",
    pitfall: "pasting untrusted Markdown then rendering raw HTML on a public site",
    interpretation: "sanitize downstream; this converter is for author-controlled text",
    relatedIntent: "use JSON formatter when the same page mixes config examples and Markdown",
    faq: [
      { question: "Are GitHub tables supported?", answer: "Not in this subset; use a full Markdown processor for tables." },
      { question: "Does it allow raw HTML in Markdown?", answer: "User HTML should be avoided; output is meant from plain Markdown constructs." },
      { question: "Large documents?", answer: "Split very large files to keep the tab responsive." },
    ],
  },
  "unix-timestamp-converter": {
    audience: "engineers correlating logs, JWT exp, and webhook delivery timestamps",
    scenario: "convert epoch seconds from a log line to ISO UTC for a postmortem doc",
    exampleInput: "1735689600",
    exampleOutput: "2025-01-01T00:00:00.000Z style ISO string",
    pitfall: "mixing milliseconds and seconds without checking digit length",
    interpretation: "normalize to UTC in writing, then let readers convert timezones locally",
    relatedIntent: "pair with JWT decoder when reading exp alongside header metadata",
    faq: [
      { question: "Why 13 digits?", answer: "JavaScript Date often works in ms; we normalize 13-digit inputs to seconds." },
      { question: "Local timezone output?", answer: "Primary line is UTC; local wall clocks are intentionally out of scope." },
      { question: "Negative epochs?", answer: "Supported for pre-1970 instants when parsed numerically." },
    ],
  },
  "gst-calculator-australia": {
    audience: "Australian freelancers and SMB owners sanity-checking invoices",
    scenario: "splitting a GST-inclusive total into net + 10% component before issuing a credit note draft",
    exampleInput: "110 AUD GST-inclusive total from a client invoice",
    exampleOutput: "100 AUD net, 10 AUD GST (divide inclusive by 1.1, do not multiply inclusive by 10%)",
    pitfall: "applying 10% to the inclusive figure instead of dividing by 1.1",
    interpretation: "label whether your input is net or gross before sharing numbers",
    relatedIntent: "compare mentally with VAT tools when you also sell overseas",
    faq: [
      { question: "Does this cover GST-free supplies?", answer: "No; supply classification stays with you and your advisor." },
      { question: "Rounding to cents?", answer: "Outputs round to two decimals; invoice systems may differ on line rounding." },
      { question: "ATO official rates?", answer: "Standard rate modeled at 10%; exemptions are not enumerated here." },
      {
        question: "Worked example for inclusive pricing?",
        answer: "If you receive 1,100 inclusive, divide by 1.1 to get 1,000 net and 100 GST. Multiplying 1,100 by 10% would overstate GST because the base already includes tax.",
      },
    ],
  },
  "zakat-calculator": {
    audience: "households tracking zakatable wealth across cash and bullion with scholar-guided nisab",
    scenario: "checking whether wealth clears a nisab line before applying 2.5%",
    exampleInput: "wealth 12,000; nisab 6,000; rate 2.5%",
    exampleOutput: "150 due on 6,000 surplus (12,000 wealth minus 6,000 nisab, then 2.5% of the remainder)",
    pitfall: "using a stale bullion nisab when local guidance moved with spot prices",
    interpretation: "enter the nisab threshold your authority uses for the lunar year",
    relatedIntent: "use currency converter when assets span FX before summing wealth",
    faq: [
      { question: "Is this a religious ruling?", answer: "No; arithmetic only; consult qualified scholars for eligibility." },
      { question: "Business inventory?", answer: "Model inventory and receivables separately before entering total zakatable wealth." },
      { question: "Debts deductible?", answer: "Subtract qualifying debts per your guidance before entering wealth." },
      {
        question: "How do I keep FX consistent across accounts?",
        answer:
          "Convert each balance to the currency you will use for nisab comparison using one dated FX table, then sum. Mixing daily rates across banks can shift the surplus line by a meaningful amount.",
      },
    ],
  },
  "freelance-day-rate-calculator": {
    audience: "consultants pricing retained days instead of hourly retainers",
    scenario: "backing into a day rate from an annual after-tax goal and ~120 billable days",
    exampleInput: "120k target, 120 days, 30% tax margin",
    exampleOutput: "gross-up annual need then per-day floor",
    pitfall: "forgetting non-billable sales and admin time already baked into billable days",
    interpretation: "lower billable days before lowering the rate when reality bites",
    relatedIntent: "compare with the hourly freelance rate tool for hybrid quotes",
    faq: [
      { question: "Does this include super or VAT?", answer: "No; fold statutory costs into your annual target or margin first." },
      { question: "Half-day bookings?", answer: "Derive an implicit hourly from day rate ÷ expected hours per day." },
      { question: "Public holidays?", answer: "Reduce billable days to reflect real working calendars in your region." },
    ],
  },
  "employee-cost-calculator": {
    audience: "finance partners and hiring managers estimating loaded seat cost",
    scenario: "adding 25% benefits load and 15% overhead on a 95k salary for budgeting",
    exampleInput: "95000 salary, 25% benefits, 15% overhead",
    exampleOutput: "single loaded annual figure plus intermediate lines",
    pitfall: "double-counting contractors who already embed overhead in their rate",
    interpretation: "use for W-2 style packages, not 1099 day rates unless you normalize",
    relatedIntent: "pair with break-even calculators when pricing SaaS that is headcount-heavy",
    faq: [
      { question: "Equity comp?", answer: "Exclude or add manually; RSU expense policies vary." },
      { question: "Multi-country teams?", answer: "Use country-specific burden rates per seat before summing." },
      { question: "Part-time?", answer: "Prorate salary first, then apply percentages." },
    ],
  },
  "invoice-late-fee-calculator": {
    audience: "AR clerks and freelancers writing late-fee clauses",
    scenario: "simple interest on 30+ day overdue invoices at a contracted annual percent",
    exampleInput: "5000 principal, 22 days, 12% contractual",
    exampleOutput: "fee line plus total due snapshot",
    pitfall: "exceeding legal usury caps for consumer-facing contracts",
    interpretation: "confirm permissible rates with counsel before enforcing",
    relatedIntent: "use GST calculator when the invoice also needs tax split",
    faq: [
      { question: "Compound interest?", answer: "This path is simple interest; compound needs another model." },
      { question: "360-day basis?", answer: "We use 365; adjust the effective rate if your contract says 360." },
      { question: "Partial payments?", answer: "Reduce principal in your books before late periods in real life." },
    ],
  },
  "stone-to-kg-converter": {
    audience: "UK readers translating body weight and shipping notes",
    scenario: "converting 11 stone to kilograms for a medical form asking metric",
    exampleInput: "11 st",
    exampleOutput: "69.85 kg (six decimals shown)",
    pitfall: "mixing stone with separate pounds without normalizing to decimal stone first",
    interpretation: "carry extra precision internally, round for display per form rules",
    relatedIntent: "use feet/inches to cm when the same intake form asks height",
    faq: [
      { question: "How many pounds in a stone?", answer: "Exactly 14 pounds per stone in this conversion path." },
      { question: "US customary weights?", answer: "Stone is uncommon in the US; pounds+ounces tools may fit better." },
      { question: "Reverse conversion?", answer: "Use the direction selector to convert kilograms back to stone." },
    ],
  },
  "feet-inches-to-cm-converter": {
    audience: "travelers, athletes, and clinicians converting imperial height to metric",
    scenario: "5 ft 10 in expressed as centimeters on an international visa health form",
    exampleInput: "5 ft 10 in",
    exampleOutput: "177.8 cm range with inch precision",
    pitfall: "entering 12+ inches without rolling into the next foot",
    interpretation: "normalize inches to <12 when possible for familiar human-readable heights",
    relatedIntent: "pair with stone-to-kg when both mass and height are requested",
    faq: [
      { question: "Decimal inches?", answer: "Supported for fractional inches like 10.5." },
      { question: "cm back to ft/in?", answer: "Use the cm → ft/in direction and ignore feet/in fields." },
      { question: "Medical rounding?", answer: "Follow clinic policy; this tool shows high precision math." },
    ],
  },
  "acres-to-hectares-converter": {
    audience: "farmers, GIS beginners, and property readers skimming international listings",
    scenario: "converting a 40 acre field note into hectares for a EU partner deck",
    exampleInput: "40 ac",
    exampleOutput: "16.18742569 ha (international acre definition)",
    pitfall: "using US survey acres for legal descriptions without checking title documents",
    interpretation: "label which acre definition your deed references when precision matters",
    relatedIntent: "use km/mile tools when the same project also discusses perimeter access roads",
    faq: [
      { question: "International vs US survey acre?", answer: "This tool uses international acre; survey acres differ slightly." },
      { question: "Square meters?", answer: "Multiply hectares by 10,000 for flat conversions." },
      { question: "GPS area polygons?", answer: "Use geodesic area tools; this is flat unit conversion only." },
    ],
  },
};
