import type { Phase1Profile } from "./phase1-seo";

/** Deep SEO profiles for Phase 2 expansion tools (merged in `content.ts`). */
export const expansionPhase2Profiles: Record<string, Phase1Profile> = {
  "html-formatter": {
    audience: "front-end engineers cleaning snippets before code review",
    scenario: "one-line HTML from a minified bundle needs readable structure in Slack",
    exampleInput: "<ul><li>a</li><li>b</li></ul>",
    exampleOutput: "tags split onto separate lines",
    pitfall: "assuming pretty spacing fixes broken nesting",
    interpretation: "treat as a readability pass before IDE formatters",
    relatedIntent: "open JSON formatter when the same incident mixes API bodies and markup",
    faq: [
      { question: "Does it fix missing closing tags?", answer: "No; invalid trees stay invalid." },
      { question: "Inline scripts?", answer: "Large JS blocks may stay dense; use a JS-aware formatter." },
    ],
  },
  "css-minifier": {
    audience: "developers shipping small CSS bundles to edge workers",
    scenario: "strip comments from a hand-written theme before upload",
    exampleInput: "/* hero */ .hero { padding: 1rem; }",
    exampleOutput: "compact single-line CSS",
    pitfall: "removing license headers required by third-party libraries",
    interpretation: "keep originals in git and minify in CI when possible",
    relatedIntent: "pair with HTML formatter when extracting critical CSS",
    faq: [
      { question: "Safe for Tailwind output?", answer: "Usually yes; still verify in devtools after purge." },
      { question: "Keyframes spacing?", answer: "Re-test animations after aggressive minification." },
    ],
  },
  "json-minifier": {
    audience: "API engineers building deterministic cache keys",
    scenario: "POST body must be one line for a signed payload example",
    exampleInput: '{ "a": 1 }',
    exampleOutput: '{"a":1}',
    pitfall: "minifying before validating schema",
    interpretation: "parse errors surface clearly before deployment",
    relatedIntent: "use JSON validator when debugging upstream rejects",
    faq: [
      { question: "Preserves Unicode?", answer: "JSON.stringify rules apply; escapes may change." },
      { question: "BigInt?", answer: "JSON.parse may throw; handle big integers outside this tool." },
    ],
  },
  "xml-formatter": {
    audience: "integrators reading SOAP/XML-RPC traces",
    scenario: "log line contains `<Envelope><Body>` without newlines",
    exampleInput: "<a><b>1</b></a>",
    exampleOutput: "line-broken tags",
    pitfall: "pretty layout implying schema validity",
    interpretation: "validate XSD separately before mutating payloads",
    relatedIntent: "switch to YAML validator when configs are YAML-native",
    faq: [
      { question: "Supports namespaces?", answer: "Tag breaks only; namespace semantics unchanged." },
      { question: "Huge payloads?", answer: "Split files to keep the tab responsive." },
    ],
  },
  "yaml-validator": {
    audience: "platform engineers editing Helm values locally",
    scenario: "indentation error blocks deploy; need fast parse feedback",
    exampleInput: "key:\n  child: 1",
    exampleOutput: "root type map",
    pitfall: "assuming parse success equals cluster safety",
    interpretation: "follow with kubeconform or server-side dry runs",
    relatedIntent: "use CSV to JSON when seeding tabular fixtures",
    faq: [
      { question: "Anchors & aliases?", answer: "Supported when the parser accepts them." },
      { question: "JSON as YAML?", answer: "Valid YAML 1.2; paste JSON to verify syntax." },
    ],
  },
  "csv-to-json-converter": {
    audience: "data folks prototyping APIs from spreadsheet exports",
    scenario: "product manager sends Excel CSV for a mock API",
    exampleInput: "sku,price\nA1,9.99",
    exampleOutput: "array of row objects",
    pitfall: "commas inside unquoted cells breaking columns",
    interpretation: "quote fields that contain delimiters",
    relatedIntent: "open SQL formatter when the same data lands in warehouses",
    faq: [
      { question: "Semicolon CSV?", answer: "Convert delimiters first." },
      { question: "Typed numbers?", answer: "Outputs strings per cell; cast downstream." },
    ],
  },
  "jwt-expiry-checker": {
    audience: "full-stack devs debugging session timeouts",
    scenario: "support ticket asks if token should still be valid",
    exampleInput: "JWT with numeric exp claim",
    exampleOutput: "minutes remaining vs now",
    pitfall: "trusting exp without verifying issuer signature",
    interpretation: "pair with server logs for skew and revocation",
    relatedIntent: "use Unix timestamp converter when comparing iat across systems",
    faq: [
      { question: "Clock skew?", answer: "Compare server clocks; one minute matters near expiry." },
      { question: "Refresh tokens?", answer: "Opaque strings are not JWT-shaped here." },
    ],
  },
  "api-status-checker": {
    audience: "SREs drafting curl probes for new endpoints",
    scenario: "paste staging URL before sharing runbook",
    exampleInput: "https://api.example.com/health",
    exampleOutput: "curl -sI command string",
    pitfall: "expecting live HTTP codes inside sync calculator",
    interpretation: "run curl/Postman for authoritative status and TLS details",
    relatedIntent: "use API response formatter when you have JSON bodies, not just URLs",
    faq: [
      { question: "Why no 200 line?", answer: "Async network calls are not executed in this engine path." },
      { question: "Auth headers?", answer: "Add curl -H flags manually from your secret store." },
    ],
  },
  "self-employed-tax-calculator-uk": {
    audience: "UK sole traders modeling cash after tax and NI sketches",
    scenario: "year-end profit forecast before payments on account",
    exampleInput: "profit 48000, blended income tax 18%, NI 6% (from accountant summary)",
    exampleOutput: "≈36,480 after applying combined 24% on profit (illustrative only)",
    pitfall: "typing statutory rates instead of blended effective %",
    interpretation: "pull effective % from your accountant pack",
    relatedIntent: "compare with salary-after-tax UK when considering PAYE side gigs",
    faq: [
      { question: "Class 2 vs 4?", answer: "Combine into NI % unless you model bands externally." },
      { question: "Dividends?", answer: "Use the dividend tool for distribution layers." },
      {
        question: "Payments on account?",
        answer: "This view is annual cash after rates; timing of HMRC payments on account is not modeled. Keep a separate cash calendar when liquidity matters.",
      },
      {
        question: "Student loans or pension salary sacrifice?",
        answer: "Fold them into the effective tax and NI percentages you enter, or run a PAYE-focused salary tool when those levers dominate.",
      },
    ],
  },
  "dividend-tax-calculator-uk": {
    audience: "limited company directors planning distributions",
    scenario: "board deck needs net dividend after effective tax",
    exampleInput: "gross dividend 10,000 at 25% effective tax (allowances already merged into the %)",
    exampleOutput: "7,500 net sketch for board slides",
    pitfall: "ignoring allowance stacking with salary",
    interpretation: "merge allowances into the % you enter",
    relatedIntent: "pair with self-employed tool when mixing income types",
    faq: [
      { question: "Scottish income tax?", answer: "Reflect in the effective % you supply." },
      { question: "ISA wrappers?", answer: "Exclude ISA dividends from taxable inputs." },
      {
        question: "How do I derive the effective %?",
        answer:
          "Use your tax forecast or prior-year computation to blend the dividend allowance, income tax bands, and any other income that uses the allowance first. Enter the resulting single % here for storytelling, not filing.",
      },
    ],
  },
  "stripe-fee-calculator": {
    audience: "finance ops reconciling Stripe balance transactions",
    scenario: "estimate net on a £120 charge with 1.5% + 20p",
    exampleInput: "amount 120 GBP, 1.5% + 0.20 fixed (domestic card assumption)",
    exampleOutput: "fee ≈2.00, net ≈118.00 before disputes or FX",
    pitfall: "forgetting international card uplifts",
    interpretation: "copy blended % from dashboard CSV exports",
    relatedIntent: "compare with PayPal fee tool for multi tender checkout",
    faq: [
      { question: "Radar or Billing?", answer: "Fold recurring platform fees into your own spreadsheet." },
      { question: "FX settlement?", answer: "Model currency conversion outside this simple fee line." },
      {
        question: "Worked line-item check?",
        answer: "Percent applies to the charge amount first, then add the fixed pence. If your statement shows a higher blended %, increase the percent field until it matches a recent CSV export.",
      },
    ],
  },
  "paypal-fee-calculator": {
    audience: "marketplace sellers pricing multi-channel SKUs",
    scenario: "match PayPal commercial rate table for domestic cards",
    exampleInput: "sale 80, 2.9%, 0.30",
    exampleOutput: "net after fees",
    pitfall: "micropayment tiers vs standard tiers",
    interpretation: "swap % and fixed when your account uses micro-pricing",
    relatedIntent: "open eBay fee tool when listings route through managed payments",
    faq: [
      { question: "Chargeback?", answer: "Reserve losses separately; not modeled here." },
      { question: "Friends & family?", answer: "Different fee schedule; usually zero." },
    ],
  },
  "etsy-fee-calculator": {
    audience: "handmade sellers pricing inclusive of renewal and processing",
    scenario: "new listing stack with transaction + payment %",
    exampleInput: "price 40, listing 0.20, 6.5% + 4%",
    exampleOutput: "net after summed percents",
    pitfall: "ignoring regulatory or ad surcharges",
    interpretation: "adjust percents monthly from Etsy CSV",
    relatedIntent: "compare with Stripe standalone checkout fees",
    faq: [
      { question: "Offsite ads?", answer: "Increase % when mandatory ad fee applies." },
      { question: "Multi-item carts?", answer: "Run per line or aggregate depending on fee base." },
    ],
  },
  "ebay-fee-calculator": {
    audience: "resellers repricing with managed payments fee stack",
    scenario: "final value percent plus fixed closing fee",
    exampleInput: "sold 150, 12.8% + 0.30",
    exampleOutput: "net after FVF sketch",
    pitfall: "category caps and promoted listings",
    interpretation: "copy blended % from monthly invoice detail",
    relatedIntent: "pair with unit price calculator for bundle splits",
    faq: [
      { question: "Promoted listings?", answer: "Add ad spend as separate rows." },
      { question: "Refunded FVF?", answer: "Timing rules differ; not modeled." },
    ],
  },
  "churn-calculator": {
    audience: "SaaS operators teaching exponential decay intuition",
    scenario: "board asks what 3% monthly churn implies in 12 months",
    exampleInput: "1000 customers, 3% churn, 12 months",
    exampleOutput: "remaining customer estimate",
    pitfall: "assuming constant churn across mature cohorts",
    interpretation: "graduate to cohort charts in BI tools",
    relatedIntent: "open LTV SaaS calculator when tying churn to gross margin",
    faq: [
      { question: "Annual churn?", answer: "Convert to monthly or stretch months input." },
      { question: "Expansion revenue?", answer: "Use NRR dashboards; not this logo-only model." },
    ],
  },
  "roas-calculator": {
    audience: "performance marketers normalizing channel reports",
    scenario: "attributed revenue 24000 vs spend 6000",
    exampleInput: "revenue 24000, spend 6000",
    exampleOutput: "4.0× ROAS (24,000 ÷ 6,000); contribution ROAS still needs COGS subtracted outside this tool",
    pitfall: "mixing different attribution windows across channels",
    interpretation: "label window (click vs view, 7d vs 28d) in your notes",
    relatedIntent: "compare with marketing ROI calculator for percent framing",
    faq: [
      { question: "Blended ROAS?", answer: "Sum revenue and spend first, then calculate." },
      { question: "Margin-aware?", answer: "Subtract COGS externally for contribution ROAS." },
      {
        question: "What if one channel is view-through and another is click-only?",
        answer: "Normalize attribution labels before blending. ROAS is only comparable when the numerator and denominator share the same window and credit model.",
      },
    ],
  },
  "working-days-calculator-uk": {
    audience: "UK payroll admins counting weekdays in a pay period",
    scenario: "January payroll needs Mon–Fri days minus two bank holidays",
    exampleInput: "2026-01-05 to 2026-01-30 minus 2",
    exampleOutput: "weekday count after manual holiday subtraction",
    pitfall: "forgetting Scotland-only holidays in mixed teams",
    interpretation: "enter only holidays that hit your contract geography",
    relatedIntent: "use generic business days tool without holiday subtraction for global SLAs",
    faq: [
      { question: "Inclusive dates?", answer: "Both endpoints count if they land on weekdays." },
      { question: "Embedded UK calendar?", answer: "No; you supply holiday counts explicitly." },
    ],
  },
  "business-days-calculator": {
    audience: "customer success teams estimating SLA business days",
    scenario: "count weekdays between ticket opened and due",
    exampleInput: "2026-03-01 to 2026-03-31",
    exampleOutput: "Mon–Fri count",
    pitfall: "skipping public holidays that contracts exclude",
    interpretation: "subtract holiday overlaps manually or extend this pattern in sheets",
    relatedIntent: "pair with date difference tool for raw calendar span context",
    faq: [
      { question: "Weekend work?", answer: "Still excluded from weekday tally here." },
      { question: "Half days?", answer: "Not supported; round per policy." },
    ],
  },
  "random-team-generator": {
    audience: "facilitators randomizing breakout groups fairly",
    scenario: "18 people into 4 teams quickly on Zoom",
    exampleInput: "paste roster + team count 4",
    exampleOutput: "balanced random teams",
    pitfall: "using Math.random for regulated lotteries",
    interpretation: "fine for workshops; use audited RNG for compliance draws",
    relatedIntent: "try random name generator when seeding demo users",
    faq: [
      { question: "Uneven teams?", answer: "Sizes differ by at most one person." },
      { question: "Same draw twice?", answer: "Click calculate again for a new shuffle." },
    ],
  },
  "lbs-to-kg-converter": {
    audience: "coaches and travelers converting imperial bodyweight",
    scenario: "170 lb gym plate to metric class",
    exampleInput: "170 lb",
    exampleOutput: "77.1107 kg",
    pitfall: "rounding before airline baggage limit comparisons",
    interpretation: "keep four decimals until final display rounding",
    relatedIntent: "flip with kg-to-lbs for round-trip sanity",
    faq: [
      { question: "Avoirdupois?", answer: "Uses standard international pound definition." },
      { question: "Stone?", answer: "Use stone converter for UK height/weight mixes." },
    ],
  },
  "feet-to-cm-converter": {
    audience: "engineers converting imperial drawings to metric CAD",
    scenario: "decimal feet 12.5 → cm for laser cut file",
    exampleInput: "12.5 ft",
    exampleOutput: "381.0 cm",
    pitfall: "mixing survey foot vs international foot",
    interpretation: "confirm title plan foot definition for land work",
    relatedIntent: "use feet+inches converter when inputs are not decimal feet",
    faq: [
      { question: "CM back to feet?", answer: "Use cm-to-feet for inverse." },
      { question: "Human height?", answer: "Feet+inches UX may feel more natural." },
    ],
  },
  "pace-calculator": {
    audience: "runners translating race chip times to training pace",
    scenario: "10 km in 52 minutes steady",
    exampleInput: "distance 10 km, 0h52m00s",
    exampleOutput: "min/km pace and km/h",
    pitfall: "using GPS distance that drifted vs course certification",
    interpretation: "enter course distance for race-specific pacing",
    relatedIntent: "convert speeds with mph-to-kmh for automotive analogies",
    faq: [
      { question: "Walk breaks?", answer: "Elapsed time includes pauses." },
      { question: "Miles mode?", answer: "Switch unit selector for mile races." },
    ],
  },
  "mph-to-kmh-converter": {
    audience: "drivers reading US gauges while thinking in km/h",
    scenario: "speed limit sign 70 mph to km/h sticker",
    exampleInput: "70 mph",
    exampleOutput: "112.5741 km/h",
    pitfall: "confusing mph with km/h on rental dashboards",
    interpretation: "multiply by 1.609344 exactly",
    relatedIntent: "pair with km-to-miles for distance analog",
    faq: [
      { question: "Knots?", answer: "Use nautical mile converters separately." },
      { question: "Mach?", answer: "Not supported; speed of sound varies." },
    ],
  },
  "square-feet-to-square-meters-converter": {
    audience: "agents listing US floor plans to EU buyers",
    scenario: "condo GLA needs dual unit marketing copy",
    exampleInput: "1200 sq ft",
    exampleOutput: "111.48 m²",
    pitfall: "survey foot vs international foot on legacy deeds",
    interpretation: "verify which foot definition your survey uses",
    relatedIntent: "jump to acres-hectares for land parcels",
    faq: [
      { question: "Gross vs net area?", answer: "Tool converts numbers you supply; labels are yours." },
      { question: "Decimals?", answer: "Six decimals help before marketing rounding." },
    ],
  },
};
