import { ToolFAQ } from "./types";

export type Phase1Profile = {
  audience: string;
  scenario: string;
  exampleInput: string;
  exampleOutput: string;
  pitfall: string;
  interpretation: string;
  relatedIntent: string;
  faq: ToolFAQ[];
};

export const phase1Profiles: Record<string, Phase1Profile> = {
  "cm-to-feet": {
    audience: "students, healthcare staff, and fitness users",
    scenario: "height conversion for forms and international records",
    exampleInput: "170 cm",
    exampleOutput: "5.5774 ft",
    pitfall: "rounding too early and reporting 5.5 ft as exact value",
    interpretation: "use 2-4 decimal places when precision matters",
    relatedIntent: "compare with kilograms-to-pounds and kilometers-to-miles conversions",
    faq: [
      { question: "How do I convert cm to feet manually?", answer: "Divide centimeters by 30.48. Example: 170 / 30.48 = 5.5774 feet." },
      { question: "Can I convert cm to feet and inches?", answer: "Yes. Convert to feet first, then multiply the decimal part by 12 for inches." },
      { question: "Is this suitable for medical data entry?", answer: "Yes for quick conversion; follow your institution's rounding rules for final records." },
    ],
  },
  "kg-to-lbs": {
    audience: "gym users, nutrition coaches, and ecommerce sellers",
    scenario: "body weight and shipping weight conversion",
    exampleInput: "72 kg",
    exampleOutput: "158.7326 lbs",
    pitfall: "using 2.2 multiplier for exact billing calculations",
    interpretation: "for casual use 2 decimals are fine; for logistics keep 3-4",
    relatedIntent: "switch between weight and height tools in one workflow",
    faq: [
      { question: "What multiplier is used for kg to lbs?", answer: "The exact factor is 2.20462." },
      { question: "Is kg to lbs conversion reversible?", answer: "Yes. To reverse, divide pounds by 2.20462." },
      { question: "Can I use decimals like 0.25 kg?", answer: "Yes, decimal input is supported for precise conversion." },
    ],
  },
  "km-to-miles": {
    audience: "travelers, runners, and map users",
    scenario: "distance conversion between metric and imperial systems",
    exampleInput: "10 km",
    exampleOutput: "6.2137 miles",
    pitfall: "confusing miles with nautical miles",
    interpretation: "this tool returns statute miles, not nautical miles",
    relatedIntent: "pair with celsius-to-fahrenheit when planning international trips",
    faq: [
      { question: "How many miles is 1 kilometer?", answer: "1 kilometer equals 0.621371 miles." },
      { question: "Can I use this for race distances?", answer: "Yes, it is commonly used for 5K, 10K, and marathon comparisons." },
      { question: "Does this convert miles back to km?", answer: "This page is km to miles. For reverse conversion, divide by 0.621371." },
    ],
  },
  "celsius-to-fahrenheit": {
    audience: "students, travelers, and weather readers",
    scenario: "temperature conversion for weather and cooking",
    exampleInput: "25 C",
    exampleOutput: "77 F",
    pitfall: "forgetting multiplication before adding 32",
    interpretation: "negative values are valid and useful in winter forecasts",
    relatedIntent: "combine with metric-to-imperial tools for international planning",
    faq: [
      { question: "What is the formula for Celsius to Fahrenheit?", answer: "F = (C × 9/5) + 32." },
      { question: "Can I convert negative Celsius values?", answer: "Yes. Example: -10 C becomes 14 F." },
      { question: "Is this useful for recipe conversion?", answer: "Yes, especially when recipe temperatures are listed in Fahrenheit." },
    ],
  },
  "mb-to-gb": {
    audience: "developers, editors, and cloud users",
    scenario: "storage checks before upload or backup",
    exampleInput: "2048 MB",
    exampleOutput: "2 GB",
    pitfall: "mixing decimal (1000) and binary (1024) conversions",
    interpretation: "this tool uses 1024-based conversion common in computing",
    relatedIntent: "pair with JSON formatter for API and file workflows",
    faq: [
      { question: "How many MB are in 1 GB?", answer: "In this tool, 1 GB = 1024 MB." },
      { question: "Why do cloud values differ sometimes?", answer: "Some providers use decimal units (1000), while many systems use binary (1024)." },
      { question: "Can I convert very large MB values?", answer: "Yes, large values are supported for quick capacity planning." },
    ],
  },
  "loan-calculator": {
    audience: "borrowers, advisors, and finance teams",
    scenario: "monthly EMI estimation before loan applications",
    exampleInput: "principal 1,000,000, rate 12, years 5",
    exampleOutput: "monthly installment and total repayment estimate",
    pitfall: "ignoring processing fees or reducing-balance differences",
    interpretation: "treat result as planning output before lender verification",
    relatedIntent: "compare with EMI and compound-interest scenarios",
    faq: [
      { question: "Does this include processing fees?", answer: "No. Add fees separately for final cost estimation." },
      { question: "What interest type is assumed?", answer: "This calculator uses standard amortized EMI-style assumptions." },
      { question: "Can I compare two loan offers?", answer: "Yes, run both sets of inputs and compare installment plus total payable." },
    ],
  },
  "emi-calculator": {
    audience: "homebuyers and auto-loan borrowers",
    scenario: "EMI comparisons across different tenures",
    exampleInput: "principal 500,000, rate 11, months 60",
    exampleOutput: "monthly EMI with total payable",
    pitfall: "comparing monthly EMI without checking total interest",
    interpretation: "shorter tenure often raises EMI but lowers total interest",
    relatedIntent: "evaluate alternatives using loan and compound-interest tools",
    faq: [
      { question: "What does EMI stand for?", answer: "EMI means Equated Monthly Installment." },
      { question: "How can I reduce EMI?", answer: "Increase tenure, reduce principal, or negotiate lower interest rates." },
      { question: "Should I choose low EMI or low total interest?", answer: "Choose based on cash flow needs vs long-term borrowing cost." },
    ],
  },
  "compound-interest-calculator": {
    audience: "investors and long-term savers",
    scenario: "future value projection with compounding frequency",
    exampleInput: "principal 100,000, rate 10, years 10, frequency 12",
    exampleOutput: "maturity value under monthly compounding",
    pitfall: "using annual rate but forgetting compounding frequency",
    interpretation: "higher compounding frequency slightly increases maturity value",
    relatedIntent: "compare growth with inflation and retirement projections",
    faq: [
      { question: "What is compounding frequency?", answer: "It is how often interest is added to principal, such as yearly or monthly." },
      { question: "Does this support periodic contributions?", answer: "This version focuses on principal-based compounding; recurring plans can be estimated separately." },
      { question: "Can I use fractional rates?", answer: "Yes, decimal rates such as 7.5 are supported." },
    ],
  },
  "salary-after-tax-calculator": {
    audience: "employees, freelancers, and HR teams",
    scenario: "net salary estimation from gross pay",
    exampleInput: "salary 1200000, tax rate 12",
    exampleOutput: "take-home salary after tax deduction",
    pitfall: "ignoring slabs, allowances, and local payroll rules",
    interpretation: "use as first estimate before payroll-confirmed figures",
    relatedIntent: "check country pages for localized tax benchmarks",
    faq: [
      { question: "Is this an exact payroll calculator?", answer: "No, it provides an estimate using a direct tax-rate model." },
      { question: "Can I use monthly and yearly salary?", answer: "Yes, as long as salary and tax rate are in consistent periods." },
      { question: "Does it include pension deductions?", answer: "Not by default; include extra deductions separately if needed." },
    ],
  },
  "stock-profit-calculator": {
    audience: "traders and retail investors",
    scenario: "quick profit/loss checks after trades",
    exampleInput: "buy 100, sell 120, qty 50, fee 200",
    exampleOutput: "net profit after fees",
    pitfall: "forgetting brokerage and tax deductions",
    interpretation: "always evaluate net result, not gross price difference",
    relatedIntent: "link performance checks with ROI-style analysis",
    faq: [
      { question: "Can this calculate losses too?", answer: "Yes. If sell is lower than buy, the result will be negative." },
      { question: "Should fees be total or per share?", answer: "Enter total trade fee amount for best accuracy." },
      { question: "Does this include taxes?", answer: "No. Add statutory taxes to fees for a realistic net result." },
    ],
  },
  "word-counter": {
    audience: "writers, students, and editors",
    scenario: "word-limit and draft-length checks",
    exampleInput: "a 350-word draft",
    exampleOutput: "word, character, and line-level counts",
    pitfall: "counting length but ignoring readability",
    interpretation: "use counts with editing review for final quality",
    relatedIntent: "use case-converter for format cleanup before publishing",
    faq: [
      { question: "Does this count punctuation?", answer: "Character count includes visible punctuation and symbols." },
      { question: "Can I use it for meta descriptions?", answer: "Yes, character count helps optimize snippet length." },
      { question: "Is line count useful for scripts?", answer: "Yes, especially for subtitle prep and technical drafts." },
    ],
  },
  "case-converter": {
    audience: "content writers and developers",
    scenario: "quick case formatting for docs, headings, and code labels",
    exampleInput: "toolabz seo optimizer",
    exampleOutput: "TOOLABZ SEO OPTIMIZER / Toollabz Seo Optimizer",
    pitfall: "blindly title-casing abbreviations like API or SEO",
    interpretation: "review final output once for acronyms and brand names",
    relatedIntent: "pair with word counter for publishing workflows",
    faq: [
      { question: "What formats are supported?", answer: "Uppercase, lowercase, title case, and sentence case." },
      { question: "Can it handle multi-line text?", answer: "Yes, pasted blocks are converted while preserving line breaks." },
      { question: "Should I trust title case for all words?", answer: "Mostly yes, but review acronyms and proper nouns manually." },
    ],
  },
  "password-generator": {
    audience: "general users and IT admins",
    scenario: "creating strong random passwords for new accounts",
    exampleInput: "length 16 with symbols enabled",
    exampleOutput: "high-entropy password string",
    pitfall: "using short passwords or reusing old patterns",
    interpretation: "use longer lengths for banking and admin accounts",
    relatedIntent: "pair with username generator for account setup flows",
    faq: [
      { question: "What length is recommended?", answer: "At least 12 characters for regular accounts and 16+ for sensitive accounts." },
      { question: "Should symbols be enabled?", answer: "Yes, symbols increase entropy and make brute-force attacks harder." },
      { question: "Are generated passwords stored?", answer: "No, generation runs in browser and is designed for privacy." },
    ],
  },
  "json-formatter": {
    audience: "frontend/backend developers and QA engineers",
    scenario: "beautifying JSON payloads for debugging and review",
    exampleInput: "{\"name\":\"Toollabz\",\"ok\":true}",
    exampleOutput: "indented readable JSON structure",
    pitfall: "pasting invalid JSON with trailing commas",
    interpretation: "validate syntax first, then format for readability",
    relatedIntent: "switch to JSON validator for strict error checks",
    faq: [
      { question: "Will this fix invalid JSON automatically?", answer: "No. Invalid syntax must be corrected first." },
      { question: "Is whitespace-only change safe?", answer: "Yes, formatting changes display style, not data meaning." },
      { question: "Can I format large API responses?", answer: "Yes, but very large payloads may process slower in-browser." },
    ],
  },
  "color-palette-generator": {
    audience: "designers, developers, and branding teams",
    scenario: "creating shade/tint sets from a base brand color",
    exampleInput: "#7C3AED",
    exampleOutput: "cohesive palette for UI and marketing assets",
    pitfall: "using random colors without contrast checks",
    interpretation: "test generated colors on both light and dark backgrounds",
    relatedIntent: "combine with business-name generation during brand ideation",
    faq: [
      { question: "What color format should I enter?", answer: "Use a valid HEX code like #7C3AED." },
      { question: "Can I use generated colors in Tailwind or CSS?", answer: "Yes, copy HEX values directly into variables or tokens." },
      { question: "Does this guarantee accessibility contrast?", answer: "No, always verify contrast ratios for text/background combinations." },
    ],
  },
  "net-worth-calculator": {
    audience: "households, professionals, and side-hustle earners in USA, UK, Canada, and Australia",
    scenario: "monthly financial check-ins to measure asset growth and debt reduction progress",
    exampleInput: "cash 15000, investments 45000, property 280000, retirement 40000, debts 210000",
    exampleOutput: "clear net worth figure with assets, liabilities, and debt-to-asset context",
    pitfall: "counting full property value but forgetting to subtract the remaining mortgage",
    interpretation: "track trend direction over time, not just one-time number snapshots",
    relatedIntent: "pair net worth tracking with debt payoff and savings planning calculators",
    faq: [
      { question: "What counts as an asset in a net worth calculator?", answer: "Cash, investments, property value, retirement balances, and any other items you can assign a fair market value to." },
      { question: "What counts as a liability?", answer: "Mortgage balance, credit card balances, student loans, auto loans, and any other outstanding debt obligations." },
      { question: "Why does my net worth change every month?", answer: "Market values move, debts amortize, and cash flow changes. Monthly tracking reveals real progress direction over time." },
    ],
  },
  "debt-payoff-calculator-snowball": {
    audience: "budget-focused households and debt payoff planners in USA, UK, Canada, and Australia",
    scenario: "building a realistic debt elimination timeline with motivation from quick wins",
    exampleInput: "debt 18000, APR 19.9, payment 650, smallest debt 900",
    exampleOutput: "estimated payoff months, projected debt-free date, and interest cost",
    pitfall: "setting monthly payment below monthly interest accrual",
    interpretation: "use this as a planning baseline and increase monthly budget whenever possible",
    relatedIntent: "compare with avalanche strategy and card utilization optimization",
    faq: [
      { question: "Why does snowball focus on the smallest debt first?", answer: "Clearing a small balance early creates momentum and helps many users stay consistent with repayment behavior." },
      { question: "Will snowball always minimize interest?", answer: "Not always. Avalanche often lowers interest more, but snowball can improve execution consistency." },
      { question: "How often should I update my debt snowball plan?", answer: "Update monthly after statements close so your timeline reflects real balances and payment changes." },
    ],
  },
  "debt-payoff-calculator-avalanche": {
    audience: "rate-sensitive borrowers focused on minimizing interest costs",
    scenario: "prioritizing high APR debts first to reduce total borrowing cost",
    exampleInput: "debt 18000, APR 19.9, payment 650, highest APR debt 5000",
    exampleOutput: "estimated payoff months with strategy emphasis on high-interest balances",
    pitfall: "assuming all debts share the same APR when one account is much higher",
    interpretation: "use avalanche when long-term interest savings is your top priority",
    relatedIntent: "run snowball comparison to balance psychology and cost efficiency",
    faq: [
      { question: "What makes avalanche different from snowball?", answer: "Avalanche targets the highest APR debt first, while snowball targets the smallest balance first." },
      { question: "Does avalanche require perfect discipline?", answer: "It benefits from consistency; automation can help keep payments on schedule." },
      { question: "Can avalanche be used with debt consolidation plans?", answer: "Yes. You can compare post-consolidation APR against existing balances to decide next actions." },
    ],
  },
  "credit-card-interest-calculator": {
    audience: "credit card users managing revolving balances and monthly payoff plans",
    scenario: "estimating card interest burden and evaluating payment strategy impact",
    exampleInput: "balance 4200, APR 24.99, payment 180",
    exampleOutput: "monthly interest estimate, annualized cost, and payoff duration",
    pitfall: "paying only near-interest amounts and expecting rapid principal reduction",
    interpretation: "target payment levels that materially reduce principal each month",
    relatedIntent: "pair with utilization and debt payoff tools for complete card strategy",
    faq: [
      { question: "Why does credit card APR feel expensive?", answer: "APR on revolving debt compounds over time, so carrying balances can become costly quickly." },
      { question: "Should I focus on APR transfers or bigger payments first?", answer: "Both can help; evaluate transfer fees, promo terms, and your cash flow before deciding." },
      { question: "Does statement timing matter for interest?", answer: "Yes. Payment timing and average daily balance can influence charged interest." },
    ],
  },
  "credit-utilization-calculator": {
    audience: "borrowers improving credit profile before loans, mortgages, or card applications",
    scenario: "tracking aggregate and per-card utilization ratios for score optimization",
    exampleInput: "total balance 2600, total limit 12000, card balance 900, card limit 2000",
    exampleOutput: "total utilization and per-card utilization with quality band guidance",
    pitfall: "only checking total utilization while one card remains near maxed out",
    interpretation: "optimize both overall and individual card ratios before reporting dates",
    relatedIntent: "use alongside card interest and debt payoff calculators for better planning",
    faq: [
      { question: "Is 30% utilization a hard rule?", answer: "It is a common guideline, not a legal threshold; lower utilization is often favorable." },
      { question: "Can higher limits improve utilization?", answer: "Yes, if spending stays stable. A higher denominator lowers ratio percentages." },
      { question: "Should I close old credit cards to simplify accounts?", answer: "Closing cards can reduce available limit and increase utilization ratio, so evaluate carefully." },
    ],
  },
  "early-loan-payoff-calculator": {
    audience: "borrowers evaluating extra payments on mortgage, auto, and personal loans",
    scenario: "estimating months and interest saved when paying above scheduled amount",
    exampleInput: "balance 25000, APR 7.5, remaining 60 months, extra 100",
    exampleOutput: "accelerated payoff timeline, months saved, and estimated interest savings",
    pitfall: "ignoring lender prepayment penalties when comparing savings",
    interpretation: "confirm penalties and cash-reserve needs before committing extra payments",
    relatedIntent: "combine with debt payoff tools to prioritize which loan to attack first",
    faq: [
      { question: "Does every dollar of extra payment reduce interest?", answer: "For standard amortized loans, extra principal generally lowers future interest accrual." },
      { question: "Should I pay extra monthly or save and lump-sum later?", answer: "Monthly extra payments usually reduce interest earlier, but lump sums can still be effective." },
      { question: "Can I use this for fixed and variable rate loans?", answer: "Yes for planning; variable-rate outcomes may shift if rates change over time." },
    ],
  },
  "refinance-calculator-mortgage": {
    audience: "homeowners comparing refinance offers and timing decisions in the USA",
    scenario: "evaluating whether lower mortgage rates offset closing costs",
    exampleInput: "balance 320000, current 7.1%, new 6.1%, 25 years, closing 6500",
    exampleOutput: "new payment estimate, monthly savings, and break-even timeline",
    pitfall: "focusing only on monthly payment while ignoring break-even timing",
    interpretation: "refinance is strongest when you stay in the home long enough to recover closing costs",
    relatedIntent: "pair with early loan payoff and net worth planning for full housing finance strategy",
    faq: [
      { question: "What refinance rate drop is worth it?", answer: "It depends on balance, term, and costs. A smaller rate drop can still work for large balances." },
      { question: "Why does break-even matter?", answer: "It tells you how long it takes for monthly savings to recover refinance fees." },
      { question: "Should I shorten term when refinancing?", answer: "Shorter terms can reduce total interest but may raise monthly payment." },
    ],
  },
  "emergency-fund-calculator": {
    audience: "households building financial resilience against job loss or unexpected costs",
    scenario: "setting a realistic emergency savings target and tracking progress",
    exampleInput: "expenses 3200, coverage 6 months, current 4500, monthly save 500",
    exampleOutput: "fund target, remaining shortfall, and months to reach goal",
    pitfall: "underestimating true essentials and setting a target too low",
    interpretation: "review target quarterly as housing, insurance, and household costs change",
    relatedIntent: "combine with savings growth and debt payoff tools to balance liquidity and liabilities",
    faq: [
      { question: "Should emergency funds include discretionary expenses?", answer: "Usually no. Focus on essential costs needed to maintain baseline living." },
      { question: "Where should emergency savings be kept?", answer: "Typically in liquid, low-risk accounts where access is fast." },
      { question: "Can I pause emergency fund contributions?", answer: "You can adjust pace temporarily, but consistent contributions improve readiness." },
    ],
  },
  "savings-interest-calculator-usa": {
    audience: "USA savers comparing APY offers and planning long-term cash goals",
    scenario: "projecting account growth from initial deposit plus monthly contributions",
    exampleInput: "initial 5000, monthly 400, APY 4.5, 5 years",
    exampleOutput: "future balance with contribution and interest breakdown",
    pitfall: "assuming advertised APY will stay fixed for the entire horizon",
    interpretation: "run multiple APY scenarios to stress-test conservative and optimistic outcomes",
    relatedIntent: "pair with emergency fund and paycheck planning for cash-flow-aligned saving",
    faq: [
      { question: "Is APY the same as APR?", answer: "No. APY includes compounding effects while APR usually does not." },
      { question: "How sensitive is growth to APY changes?", answer: "Small APY differences can compound into meaningful long-term balance changes." },
      { question: "Should I include irregular deposits?", answer: "For best estimates, model recurring deposits first, then adjust manually for irregular additions." },
    ],
  },
  "paycheck-calculator-usa": {
    audience: "employees evaluating take-home pay and offer comparisons in the USA",
    scenario: "translating annual salary into net paycheck cash flow",
    exampleInput: "salary 85000, federal 14%, state 5%, deductions 4%, biweekly",
    exampleOutput: "gross per paycheck, net paycheck estimate, and annual take-home",
    pitfall: "using one flat tax rate without considering deductions or filing details",
    interpretation: "treat output as a planning estimate and confirm with payroll-specific withholding settings",
    relatedIntent: "combine with hourly conversion and emergency fund planning for budget setup",
    faq: [
      { question: "Why does net pay differ from salary/period?", answer: "Taxes and pre-tax/post-tax deductions reduce gross pay before take-home amount." },
      { question: "Can this replace payroll software?", answer: "No. It is for planning estimates, not official payroll processing." },
      { question: "How should I choose tax rate assumptions?", answer: "Use recent paystubs or tax planning estimates for more realistic inputs." },
    ],
  },
  "hourly-to-salary-converter-usa": {
    audience: "hourly workers and job-seekers comparing compensation offers in the USA",
    scenario: "converting hourly wages into annualized salary estimates for planning",
    exampleInput: "hourly 25, hours 40, weeks 52",
    exampleOutput: "annual 52000 plus monthly and weekly equivalents",
    pitfall: "forgetting unpaid time off or seasonal schedule gaps",
    interpretation: "adjust weeks worked for realistic annual income forecasting",
    relatedIntent: "pair with paycheck calculator to estimate net take-home from gross conversion",
    faq: [
      { question: "Is 40 hours/week always assumed?", answer: "No, you can enter your actual average weekly hours." },
      { question: "What if my schedule changes monthly?", answer: "Use a realistic average for planning, then revisit as your schedule evolves." },
      { question: "Can I estimate part-time annual income?", answer: "Yes, enter lower weekly hours and actual weeks worked." },
    ],
  },
  "paycheck-calculator-california": {
    audience: "California employees comparing offers and planning monthly take-home pay",
    scenario: "estimating paycheck net amount after federal, state, and benefit deductions",
    exampleInput: "salary 95000, federal 14%, state 6%, deductions 4%, biweekly",
    exampleOutput: "gross and net paycheck estimates for California budgeting",
    pitfall: "using flat rates without reviewing real withholding setup",
    interpretation: "use output as planning guidance, then compare against actual paystub values",
    relatedIntent: "compare with Texas and USA paycheck tools for relocation or offer decisions",
    faq: [
      { question: "Why is California take-home often lower than gross expectation?", answer: "State taxes and deductions can materially reduce per-paycheck net amount." },
      { question: "Can this estimate help with rent budgeting?", answer: "Yes, it is useful for first-pass monthly cash-flow planning." },
      { question: "Should I include retirement deductions?", answer: "Yes, include expected percentages for more realistic net estimates." },
    ],
  },
  "paycheck-calculator-texas": {
    audience: "Texas workers estimating net paycheck and salary offer value",
    scenario: "calculating take-home pay with federal taxes and payroll deductions",
    exampleInput: "salary 95000, federal 14%, deductions 4%, biweekly",
    exampleOutput: "gross and net paycheck estimates in a no-state-income-tax context",
    pitfall: "assuming no state income tax means all deductions are minimal",
    interpretation: "include benefits and withholding assumptions to avoid overestimating take-home cash",
    relatedIntent: "compare Texas and California pay outcomes for job/location choices",
    faq: [
      { question: "Does Texas really have no state income tax?", answer: "Texas has no state income tax, but federal and other deductions still apply." },
      { question: "Can this be used for budgeting before relocation?", answer: "Yes, it gives a practical pre-move paycheck estimate." },
      { question: "How do I improve estimate accuracy?", answer: "Use rates based on recent paystub withholding percentages." },
    ],
  },
  "salary-to-hourly-converter-usa": {
    audience: "employees and recruiters normalizing annual and hourly compensation",
    scenario: "converting annual salary into comparable hourly wage assumptions",
    exampleInput: "salary 78000, 40 hours/week, 52 weeks/year",
    exampleOutput: "hourly rate plus weekly and monthly equivalents",
    pitfall: "using default 2080 hours when actual schedule is lower",
    interpretation: "adjust hours and weeks for realistic comparisons across roles",
    relatedIntent: "pair with hourly-to-salary and paycheck tools for complete comp analysis",
    faq: [
      { question: "Is hourly conversion useful for salaried jobs?", answer: "Yes, it helps compare compensation across salary and hourly opportunities." },
      { question: "Should paid time off be counted in weeks?", answer: "Use the effective weeks you are paid to keep estimates realistic." },
      { question: "Can I use this with part-time salaried roles?", answer: "Yes, customize hours and weeks to your arrangement." },
    ],
  },
  "overtime-pay-calculator-usa": {
    audience: "hourly workers estimating gross earnings with overtime shifts",
    scenario: "projecting paycheck impact from overtime hours at time-and-a-half or custom rates",
    exampleInput: "rate 24, regular 40, overtime 8, multiplier 1.5",
    exampleOutput: "regular pay, overtime pay, and total gross pay",
    pitfall: "mixing overtime multiplier assumptions with incorrect base rate",
    interpretation: "verify multiplier and eligible hours against employer policy and local rules",
    relatedIntent: "feed gross estimate into paycheck calculators for net pay planning",
    faq: [
      { question: "Is overtime always paid at 1.5x in the USA?", answer: "1.5x is common but not universal; policy and regulations can vary by role and jurisdiction." },
      { question: "Can I model double-time?", answer: "Yes, enter a 2.0 multiplier if applicable." },
      { question: "Does this include taxes or deductions?", answer: "No, this tool shows gross earnings before withholdings." },
    ],
  },
  "car-loan-affordability-calculator": {
    audience: "auto buyers planning monthly payment limits before dealership shopping",
    scenario: "estimating affordable loan amount and vehicle budget from monthly constraints",
    exampleInput: "budget 550, APR 7.9, term 60 months, down payment 5000",
    exampleOutput: "affordable principal, total vehicle target, and estimated interest",
    pitfall: "excluding ownership costs like insurance, fuel, and maintenance",
    interpretation: "treat loan affordability as one piece of total car ownership affordability",
    relatedIntent: "combine with paycheck and debt tools for full monthly budget alignment",
    faq: [
      { question: "Should I stretch term to afford a pricier car?", answer: "Longer terms reduce monthly payment but often increase total interest cost." },
      { question: "How much down payment is ideal?", answer: "Higher down payment generally improves affordability and lowers financing risk." },
      { question: "Does this include taxes and registration fees?", answer: "No, add local fees separately when setting final vehicle budget." },
    ],
  },
  "mortgage-affordability-calculator-usa": {
    audience: "USA homebuyers screening budgets before pre-approval",
    scenario: "estimating affordable mortgage and home price from DTI and income",
    exampleInput: "income 9000, debt 900, DTI 36, APR 6.5, 30 years, down 40000",
    exampleOutput: "affordable mortgage amount and maximum home price estimate",
    pitfall: "ignoring taxes, insurance, and HOA in payment assumptions",
    interpretation: "treat this as a planning baseline before lender-specific underwriting",
    relatedIntent: "compare with rent-vs-buy and property ROI tools for housing strategy",
    faq: [
      { question: "Does this include property tax and insurance?", answer: "This model focuses on principal-and-interest affordability baseline." },
      { question: "Why use DTI for affordability?", answer: "DTI is a common lender benchmark for debt capacity and payment feasibility." },
      { question: "Can higher down payment increase affordability?", answer: "Yes, it can increase total target home price at the same loan burden." },
    ],
  },
  "rent-vs-buy-calculator-usa": {
    audience: "USA renters and first-time buyers comparing housing paths",
    scenario: "evaluating long-term cost difference between renting and buying",
    exampleInput: "rent 2200, buy 2800, years 7, rent increase 4%",
    exampleOutput: "total rent cost, total buy cost, and lower-cost path",
    pitfall: "using flat rent assumption in markets with regular annual increases",
    interpretation: "use this with scenario ranges to stress-test housing decisions",
    relatedIntent: "pair with mortgage affordability and emergency fund calculators",
    faq: [
      { question: "Should I include maintenance in buy cost?", answer: "Yes, realistic monthly ownership cost should include maintenance and reserves." },
      { question: "Why can rent become more expensive over time?", answer: "Annual rent increases compound and can exceed fixed monthly ownership assumptions." },
      { question: "Does this model home value growth?", answer: "No, this version focuses on cash-outflow cost comparison." },
    ],
  },
  "property-roi-calculator": {
    audience: "property investors comparing deal performance quickly",
    scenario: "calculating percentage return on property investment capital",
    exampleInput: "net gain 45000, total cost 250000",
    exampleOutput: "ROI percentage benchmark for deal comparison",
    pitfall: "excluding renovation and transaction costs from total cost",
    interpretation: "use complete cost basis to avoid overstating returns",
    relatedIntent: "combine with rental yield and mortgage tools for deeper underwriting",
    faq: [
      { question: "Can I use this for flips and rentals?", answer: "Yes, as long as net gain and total cost are measured consistently." },
      { question: "What is a good property ROI?", answer: "It depends on market, risk, leverage, and holding period assumptions." },
      { question: "Should financing be included in gain/cost?", answer: "Include financing effects if you want levered ROI comparability." },
    ],
  },
  "rental-yield-calculator-uk": {
    audience: "UK buy-to-let investors screening rental opportunities",
    scenario: "measuring gross and net rental yield from rent and property value",
    exampleInput: "rent 1450/month, price 320000, annual costs 3600",
    exampleOutput: "gross and net rental yield percentages",
    pitfall: "using gross yield only while ignoring annual recurring costs",
    interpretation: "net yield is usually more informative for realistic profitability",
    relatedIntent: "compare UK rental yield with property ROI and financing plans",
    faq: [
      { question: "Why compute both gross and net yield?", answer: "Gross is quick for screening; net better reflects true operating performance." },
      { question: "Are letting fees part of annual costs?", answer: "Yes, include management, maintenance, voids, and compliance costs where possible." },
      { question: "Does yield include capital appreciation?", answer: "No, yield focuses on rental cash return relative to property value." },
    ],
  },
  "gas-cost-calculator-road-trip": {
    audience: "drivers planning fuel budgets for long-distance travel",
    scenario: "estimating road trip gas spend from distance, MPG, and fuel price",
    exampleInput: "distance 680 miles, MPG 29, fuel 3.75, round trip yes",
    exampleOutput: "fuel gallons required and estimated gas cost",
    pitfall: "using ideal MPG instead of realistic highway + city blended efficiency",
    interpretation: "run multiple fuel-price scenarios for conservative trip budgeting",
    relatedIntent: "combine with paycheck and emergency fund planning before travel",
    faq: [
      { question: "Should I include detours in distance?", answer: "Yes, adding a buffer helps avoid underestimating fuel expense." },
      { question: "How accurate is MPG for trip forecasting?", answer: "Actual MPG varies by speed, load, terrain, and traffic conditions." },
      { question: "Can I use this for one-way or round trip?", answer: "Yes, toggle round trip option based on your travel plan." },
    ],
  },
  "salary-after-tax-calculator-california": {
    audience: "California professionals evaluating net-income impact of salary offers",
    scenario: "translating gross annual pay into realistic after-tax monthly income",
    exampleInput: "salary 100000, federal 14%, CA 6%, deductions 4%",
    exampleOutput: "estimated annual and monthly net salary in California",
    pitfall: "forgetting benefits and retirement deductions when estimating net income",
    interpretation: "use this for planning, then reconcile with real paystub withholding",
    relatedIntent: "compare against Texas, Florida, New York, and UK salary tools",
    faq: [
      { question: "Can this calculator help relocation planning?", answer: "Yes, it provides fast take-home comparisons versus other regions." },
      { question: "Why include other deductions?", answer: "Benefits and retirement contributions materially affect net pay." },
      { question: "Is California take-home always lower than no-tax states?", answer: "Often yes, but final outcomes also depend on salary level and deduction structure." },
    ],
  },
  "salary-after-tax-calculator-texas": {
    audience: "Texas workers estimating annual and monthly net salary",
    scenario: "projecting take-home pay without state income tax",
    exampleInput: "salary 100000, federal 14%, deductions 4%",
    exampleOutput: "estimated annual and monthly net salary in Texas",
    pitfall: "assuming no state tax means no significant deductions",
    interpretation: "include realistic deductions to avoid overestimating usable income",
    relatedIntent: "compare with California, Florida, and New York calculators",
    faq: [
      { question: "Does no state tax mean highest take-home?", answer: "Often higher than high-tax states, but deductions and salary structure still matter." },
      { question: "Can I model benefits deductions here?", answer: "Yes, include them in other deductions percentage." },
      { question: "Should I use this with paycheck calculators?", answer: "Yes, salary and paycheck views together improve budgeting accuracy." },
    ],
  },
  "salary-after-tax-calculator-new-york": {
    audience: "New York employees accounting for federal, state, and local tax effects",
    scenario: "estimating net salary in markets with layered tax assumptions",
    exampleInput: "salary 100000, federal 14%, state 6%, local 3%, deductions 4%",
    exampleOutput: "estimated annual and monthly take-home in New York",
    pitfall: "omitting local tax assumption where applicable",
    interpretation: "run alternate local-tax scenarios for conservative planning",
    relatedIntent: "benchmark New York take-home against California, Texas, and Florida",
    faq: [
      { question: "Is local tax required for all New York residents?", answer: "No, local tax depends on municipality and residency context." },
      { question: "Why does take-home vary by city?", answer: "Local tax and cost structure can materially change effective net income." },
      { question: "Can this estimate support offer negotiation?", answer: "Yes, it helps compare net-income outcomes across compensation packages." },
    ],
  },
  "salary-after-tax-calculator-florida": {
    audience: "Florida professionals planning monthly net income and savings capacity",
    scenario: "estimating take-home salary in a no-state-income-tax environment",
    exampleInput: "salary 100000, federal 14%, deductions 4%",
    exampleOutput: "estimated annual and monthly net salary in Florida",
    pitfall: "excluding insurance and retirement deductions from planning assumptions",
    interpretation: "pair take-home estimate with emergency fund and budget targets",
    relatedIntent: "compare Florida net-income projections against Texas and California",
    faq: [
      { question: "Does Florida salary after tax only include federal tax?", answer: "It includes federal assumptions plus any additional deduction rates you enter." },
      { question: "Can this help evaluate remote work relocation?", answer: "Yes, it provides quick net-income comparisons for planning moves." },
      { question: "Should I still estimate deductions in no-tax states?", answer: "Yes, benefits and retirement deductions still reduce net pay." },
    ],
  },
  "salary-after-tax-calculator-uk": {
    audience: "UK employees and contractors estimating post-tax annual income",
    scenario: "projecting net salary after income tax, NI, and pension deductions",
    exampleInput: "salary 60000, income tax 20%, NI 8%, pension 5%",
    exampleOutput: "estimated UK annual and monthly net salary",
    pitfall: "using one blended rate without reflecting pension contribution impact",
    interpretation: "use realistic rates and compare outcomes across contribution levels",
    relatedIntent: "benchmark UK net salary against US state calculators for global planning",
    faq: [
      { question: "Does this include National Insurance?", answer: "Yes, NI is included through the dedicated NI rate input." },
      { question: "Can pension contributions reduce take-home materially?", answer: "Yes, higher pension rates reduce current net pay but increase long-term retirement savings." },
      { question: "Is this suitable for salary offer comparisons in the UK?", answer: "Yes, it is useful for quick take-home benchmarking between offers." },
    ],
  },
  "roi-calculator-marketing": {
    audience: "growth and performance marketers optimizing paid-channel efficiency",
    scenario: "comparing campaign return across channels, creatives, and audiences",
    exampleInput: "net gain 48000, campaign cost 20000",
    exampleOutput: "marketing ROI percentage for budget allocation decisions",
    pitfall: "using gross revenue as gain without subtracting variable delivery costs",
    interpretation: "normalize gain definitions across channels before comparing ROI",
    relatedIntent: "combine with CAC and conversion metrics for fuller funnel analysis",
    faq: [
      { question: "Should I include attribution assumptions?", answer: "Yes, ROI quality depends on reliable attribution and consistent gain definitions." },
      { question: "Can I compare brand and performance campaigns?", answer: "Yes, but document different measurement windows and objectives." },
      { question: "Is ROI enough to set budget?", answer: "ROI is key, but include volume, payback speed, and capacity constraints too." },
    ],
  },
  "cac-calculator-saas": {
    audience: "SaaS founders and operators tracking go-to-market efficiency",
    scenario: "estimating cost to acquire each new paying customer",
    exampleInput: "sales+marketing 120000, new customers 240",
    exampleOutput: "CAC of 500 per customer for period benchmarking",
    pitfall: "excluding team and tooling costs from acquisition spend",
    interpretation: "track CAC trend over time and segment by channel where possible",
    relatedIntent: "pair with LTV and payback analysis for sustainable growth planning",
    faq: [
      { question: "Should CAC include salaries?", answer: "For operational truth, yes - include full acquisition-related costs." },
      { question: "Can I compute CAC monthly?", answer: "Yes, monthly tracking is common for SaaS dashboards." },
      { question: "What CAC level is healthy?", answer: "Healthy CAC depends on LTV, gross margin, and payback targets." },
    ],
  },
  "ltv-calculator-saas": {
    audience: "SaaS finance and growth teams modeling unit economics",
    scenario: "estimating customer lifetime value from ARPU, margin, and churn",
    exampleInput: "ARPU 120, gross margin 80%, churn 3%",
    exampleOutput: "LTV benchmark to compare against CAC",
    pitfall: "using churn assumptions that ignore recent retention changes",
    interpretation: "update churn and margin frequently to keep LTV estimates relevant",
    relatedIntent: "use with CAC for LTV:CAC and payback tracking",
    faq: [
      { question: "Does lower churn always increase LTV?", answer: "Yes, lower churn extends customer lifetime and increases value." },
      { question: "Should I use monthly or annual churn?", answer: "Use churn period consistent with your ARPU and reporting cadence." },
      { question: "Can LTV be overestimated easily?", answer: "Yes, optimistic churn and margin assumptions can inflate projections." },
    ],
  },
  "break-even-calculator-business": {
    audience: "business owners and operators planning pricing and sales targets",
    scenario: "finding unit volume required to cover fixed and variable costs",
    exampleInput: "fixed 50000, price 120, variable 45",
    exampleOutput: "break-even units and break-even revenue target",
    pitfall: "ignoring variable costs that scale with each sale",
    interpretation: "combine break-even results with realistic sales velocity assumptions",
    relatedIntent: "pair with margin and ROI calculators for planning loops",
    faq: [
      { question: "Can break-even help pricing decisions?", answer: "Yes, contribution margin directly impacts required unit volume." },
      { question: "Why do fixed costs matter?", answer: "Higher fixed costs raise the minimum revenue required to avoid losses." },
      { question: "Is break-even enough for forecasting?", answer: "It is foundational, but add demand and cash-flow assumptions for full forecasts." },
    ],
  },
  "profit-margin-calculator-business": {
    audience: "operators monitoring profitability across products and periods",
    scenario: "calculating margin percentage to assess operating health",
    exampleInput: "revenue 250000, cost 175000",
    exampleOutput: "margin percentage for performance benchmarking",
    pitfall: "mixing inconsistent revenue and cost periods",
    interpretation: "keep definitions consistent for trustworthy trend analysis",
    relatedIntent: "combine margin, break-even, and CAC/LTV for full unit economics",
    faq: [
      { question: "Why track margin monthly?", answer: "Monthly tracking surfaces pricing pressure and cost shifts earlier." },
      { question: "Can margin improve without revenue growth?", answer: "Yes, cost optimization can raise margin at flat revenue." },
      { question: "Should one-time costs be included?", answer: "Include or exclude consistently depending on reporting purpose." },
    ],
  },
  "ai-email-subject-line-generator": {
    audience: "marketers and founders optimizing email campaign open rates",
    scenario: "generating targeted subject line variants aligned with campaign intent",
    exampleInput: "topic: onboarding upgrade offer, audience: trial users, tone: urgent",
    exampleOutput: "multiple audience-aware subject line options for A/B testing",
    pitfall: "using generic subject lines that do not reflect audience context",
    interpretation: "test 2-4 variants and keep naming consistent with email body promise",
    relatedIntent: "pair with open-rate and click-rate tools to validate performance",
    faq: [
      { question: "Can this help lifecycle emails too?", answer: "Yes, it works for onboarding, activation, upsell, and retention campaigns." },
      { question: "Should subject lines mention audience segment?", answer: "Often yes, segment-aware language can increase relevance." },
      { question: "Is urgency always better?", answer: "Not always; test urgency against trust and clarity for your audience." },
    ],
  },
  "ai-cold-email-generator": {
    audience: "SDRs, founders, and agencies scaling outbound prospecting",
    scenario: "building first-draft outreach emails from offer and prospect context",
    exampleInput: "offer: CRO audit, audience: ecommerce brands, cta: 15-min call",
    exampleOutput: "context-specific cold email draft with clear CTA",
    pitfall: "sending untouched templates without account-level personalization",
    interpretation: "use generated draft as base, then add one precise prospect insight",
    relatedIntent: "combine with subject line generation and conversion tracking",
    faq: [
      { question: "Will this produce compliant outreach automatically?", answer: "It provides draft copy; you should still review legal and policy requirements." },
      { question: "Can I use this for warm intros?", answer: "Yes, adapt tone and shorten framing for warmer contexts." },
      { question: "How much should I edit before sending?", answer: "At minimum, add personalized references and remove generic placeholders." },
    ],
  },
  "ai-linkedin-post-generator": {
    audience: "professionals and brands building audience through consistent social publishing",
    scenario: "turning topic and goal into structured LinkedIn post drafts",
    exampleInput: "topic: churn reduction playbook, audience: SaaS founders, goal: demo requests",
    exampleOutput: "hook-driven post with value bullets and contextual CTA",
    pitfall: "posting generic statements without proof, examples, or useful framing",
    interpretation: "add one real metric, example, or lesson to improve authenticity",
    relatedIntent: "pair with engagement and funnel tools for channel performance insights",
    faq: [
      { question: "Should I post daily or weekly?", answer: "Consistency matters more than volume; choose a pace you can sustain with quality." },
      { question: "Can this generate educational threads?", answer: "Yes, expand each bullet into standalone mini-posts if needed." },
      { question: "How do I avoid generic posts?", answer: "Include audience-specific pain points and concrete outcomes." },
    ],
  },
  "ai-resume-summary-generator": {
    audience: "job seekers tailoring applications for specific roles",
    scenario: "creating concise role-focused resume summaries with measurable impact",
    exampleInput: "role: product manager, exp: 7, skills: roadmap+analytics, achievement: +32% activation",
    exampleOutput: "targeted summary statement that highlights fit and outcomes",
    pitfall: "using broad claims without measurable achievement evidence",
    interpretation: "keep summary concise and align wording to each job description",
    relatedIntent: "repurpose summary for profile headlines and tailored application variants",
    faq: [
      { question: "Should I customize summary for every role?", answer: "Yes, role-specific alignment improves recruiter relevance quickly." },
      { question: "Can this help career changers?", answer: "Yes, emphasize transferable skills and outcomes in your inputs." },
      { question: "How many achievements should I mention?", answer: "One strong quantified achievement is usually enough in summary section." },
    ],
  },
  "ai-product-description-generator": {
    audience: "ecommerce teams and founders improving product-page clarity",
    scenario: "generating benefit-led product copy from features and audience context",
    exampleInput: "product: ergonomic stand, audience: remote workers, features: adjustable height, aluminum build",
    exampleOutput: "conversion-oriented description connecting features to user outcomes",
    pitfall: "listing features only without explaining customer benefit",
    interpretation: "map each feature to one practical outcome in final edited version",
    relatedIntent: "pair with landing-page and ROI tools to optimize revenue impact",
    faq: [
      { question: "Can this help SEO on product pages?", answer: "Yes, include relevant keywords naturally and avoid stuffing." },
      { question: "Should descriptions be long or short?", answer: "Use concise core copy with scannable supporting bullets for clarity." },
      { question: "Can I reuse one description across channels?", answer: "Base copy can be reused, but adapt length and tone per channel." },
    ],
  },
  "json-validator": {
    audience: "developers and QA engineers validating JSON payloads quickly",
    scenario: "catching malformed JSON before API calls, deployments, or data imports",
    exampleInput: "{\"user\":{\"id\":12,\"active\":true}}",
    exampleOutput: "valid JSON confirmation or precise parse error feedback",
    pitfall: "copying JavaScript-style objects with trailing commas into strict JSON parsers",
    interpretation: "validate early to prevent downstream parsing failures",
    relatedIntent: "use with API response formatter and JSON formatter for complete payload debugging",
    faq: [
      { question: "Does this validator check schema compliance?", answer: "No, it validates syntax/parseability. Schema checks require additional rules." },
      { question: "Can I validate large JSON responses?", answer: "Yes, though very large payloads may take longer to process in-browser." },
      { question: "Will it auto-fix invalid JSON?", answer: "No, it highlights validity so you can correct source data safely." },
    ],
  },
  "base64-encoder-decoder": {
    audience: "developers working with APIs, tokens, and transport-safe encoding",
    scenario: "encoding and decoding Base64 values for integrations and debugging",
    exampleInput: "encode: hello world / decode: aGVsbG8gd29ybGQ=",
    exampleOutput: "correct encoded or decoded value",
    pitfall: "treating Base64 encoding as data encryption",
    interpretation: "use Base64 for representation, not security",
    relatedIntent: "combine with URL and JSON tools for full request/response debugging",
    faq: [
      { question: "Can Base64 break with non-UTF text?", answer: "Some character sets can require additional handling depending on environment." },
      { question: "Is Base64 reversible?", answer: "Yes, encoded text can be decoded back when input is valid." },
      { question: "Should I store secrets in Base64?", answer: "No, use encryption/secret management instead of plain encoding." },
    ],
  },
  "url-encoder-decoder": {
    audience: "developers handling query strings and encoded URL components",
    scenario: "making parameters URL-safe and decoding encoded request values",
    exampleInput: "hello world?x=1&y=2",
    exampleOutput: "hello%20world%3Fx%3D1%26y%3D2",
    pitfall: "double-encoding already encoded values",
    interpretation: "encode only the parts that need escaping to avoid malformed links",
    relatedIntent: "pair with regex and API formatting tools for endpoint debugging",
    faq: [
      { question: "Should I encode full URL or only parameter values?", answer: "Usually encode dynamic parameter values, not full URL structure." },
      { question: "Why does decode sometimes fail?", answer: "Invalid percent-encoding sequences can throw decode errors." },
      { question: "Can this help fix broken callback URLs?", answer: "Yes, it helps inspect and normalize encoded URL segments." },
    ],
  },
  "regex-tester": {
    audience: "developers and analysts building reliable text-matching rules",
    scenario: "testing patterns against sample data before shipping validation logic",
    exampleInput: "pattern: ^[a-z0-9_]{3,16}$ with flags: i",
    exampleOutput: "match count and sample matches for quick pattern verification",
    pitfall: "forgetting anchors or escape sequences and matching unintended text",
    interpretation: "iterate patterns with representative test data before production use",
    relatedIntent: "combine with JSON and API tools for robust parsing pipelines",
    faq: [
      { question: "Can I test global and multiline flags together?", answer: "Yes, provide combined flags like gm when needed." },
      { question: "Why is my regex too slow?", answer: "Complex backtracking patterns can degrade performance on long inputs." },
      { question: "Does this support capture group preview?", answer: "It focuses on match outputs; use targeted patterns for group-specific debugging." },
    ],
  },
  "api-response-formatter": {
    audience: "frontend/backend developers inspecting API response payloads",
    scenario: "formatting and validating raw JSON responses during debugging and QA",
    exampleInput: "{\"status\":\"ok\",\"data\":{\"items\":[1,2,3]}}",
    exampleOutput: "pretty-printed response with top-level key summary",
    pitfall: "debugging API issues against minified or malformed response text",
    interpretation: "format first, then inspect key structure to isolate integration issues faster",
    relatedIntent: "use with JSON validator and regex tester for complete API troubleshooting",
    faq: [
      { question: "What extra value does this provide over JSON formatter?", answer: "It focuses on API responses and includes top-level key summary for quick inspection." },
      { question: "Can I use this with webhook payloads?", answer: "Yes, webhook JSON can be validated and formatted the same way." },
      { question: "Does this support non-JSON API responses?", answer: "No, this tool targets JSON response formatting and validation." },
    ],
  },
  "moving-cost-calculator-usa": {
    audience: "households planning local and long-distance relocations in the USA",
    scenario: "estimating realistic moving budget before booking services",
    exampleInput: "distance 1200 miles, 4 rooms, labor 12h, rate 95, truck 1800, supplies 250",
    exampleOutput: "estimated total move cost with labor and distance components",
    pitfall: "underestimating packing and transport overheads",
    interpretation: "run conservative and optimistic scenarios before committing contracts",
    relatedIntent: "pair with monthly budget and emergency fund planning before relocation",
    faq: [
      { question: "Can I use this for local moves too?", answer: "Yes, set shorter distance and realistic labor assumptions." },
      { question: "Should I include temporary housing costs?", answer: "Add temporary housing separately for full relocation budgeting." },
      { question: "How accurate is this estimate?", answer: "It is a planning estimate; final quotes vary by provider and service scope." },
    ],
  },
  "electricity-cost-calculator-usa": {
    audience: "households comparing appliance energy impact on monthly utility bills",
    scenario: "estimating cost of appliance usage using kWh billing assumptions",
    exampleInput: "1500W heater, 4h/day, 30 days, $0.18/kWh",
    exampleOutput: "monthly kWh usage and estimated electricity spend",
    pitfall: "using incorrect wattage or unrealistic usage durations",
    interpretation: "measure major appliances and optimize usage to reduce bill volatility",
    relatedIntent: "use with monthly budget planner for utility cost control",
    faq: [
      { question: "Does standby power matter?", answer: "Yes, always-on devices can add up over a full month." },
      { question: "Can I compare two appliances?", answer: "Yes, run separate estimates with each wattage profile." },
      { question: "Is this suitable for annual planning?", answer: "Yes, multiply monthly estimate for quick annual rough budgeting." },
    ],
  },
  "internet-speed-requirement-calculator": {
    audience: "households and small teams choosing internet plans",
    scenario: "estimating download speed needs based on concurrent usage mix",
    exampleInput: "4 users, 2 streams, 2 video calls, 1 gaming device, 25% buffer",
    exampleOutput: "recommended Mbps tier and suggested plan band",
    pitfall: "buying plans based on user count only without activity profile",
    interpretation: "focus on concurrent heavy activities rather than total connected devices",
    relatedIntent: "combine with budget planning to optimize plan cost vs performance",
    faq: [
      { question: "Does this include upload speed recommendations?", answer: "This version prioritizes download planning; upload should be reviewed separately for creator-heavy use." },
      { question: "Should I overprovision speed?", answer: "A modest buffer helps avoid quality drops during peak use." },
      { question: "Can this support remote work setup decisions?", answer: "Yes, include concurrent call and streaming usage for realistic recommendations." },
    ],
  },
  "budget-planner-monthly-usa": {
    audience: "USA households tracking monthly cash flow and savings discipline",
    scenario: "balancing income, expenses, debt, and savings goals in one budget view",
    exampleInput: "income 6500, fixed 2600, variable 1400, debt 700, savings 800",
    exampleOutput: "monthly surplus/deficit and expense pressure indicators",
    pitfall: "setting savings targets without accounting for variable expense swings",
    interpretation: "update budget monthly and adjust categories before deficits compound",
    relatedIntent: "pair with paycheck, utility, and emergency fund calculators",
    faq: [
      { question: "How much should I allocate to savings?", answer: "Savings targets vary, but consistent monthly contributions improve resilience and goal progress." },
      { question: "What if my budget is negative?", answer: "Reduce variable spending, review fixed costs, and revisit debt strategy immediately." },
      { question: "Can this help debt payoff planning?", answer: "Yes, it shows available cash-flow capacity for extra debt payments." },
    ],
  },
  "daily-calorie-calculator": {
    audience: "people planning nutrition for maintenance, fat loss, or lean gain",
    scenario: "estimating daily calorie baseline from body metrics and activity",
    exampleInput: "male, 30y, 78kg, 178cm, moderate activity",
    exampleOutput: "maintenance calories plus suggested deficit/surplus targets",
    pitfall: "using static calorie targets while body weight and activity change",
    interpretation: "recalculate regularly and adjust based on real progress data",
    relatedIntent: "combine with budget and meal planning workflows for consistency",
    faq: [
      { question: "Is this a medical nutrition plan?", answer: "No, it is a general estimation tool for planning purposes." },
      { question: "How fast should I reduce calories for fat loss?", answer: "Moderate deficits are usually more sustainable than aggressive cuts." },
      { question: "Can activity level selection change results a lot?", answer: "Yes, activity multiplier has a significant effect on estimated daily needs." },
    ],
  },
  "business-name-generator": {
    audience: "founders and operators naming new ventures quickly",
    scenario: "generating multiple brandable business names from one niche keyword",
    exampleInput: "keyword: workflow automation",
    exampleOutput: "5-10 distinct business name options for shortlist review",
    pitfall: "picking names before checking domains and trademark conflicts",
    interpretation: "shortlist 3-5 options, then validate legal and digital availability",
    relatedIntent: "combine with startup and brand naming generators for broader ideation",
    faq: [
      { question: "Can I regenerate a fresh list instantly?", answer: "Yes, regenerate creates a new set while keeping your keyword context." },
      { question: "How many names does this return?", answer: "Each run provides between 5 and 10 options." },
      { question: "Should I prioritize short names?", answer: "Short, memorable names often help recall and typing ease." },
    ],
  },
  "username-generator": {
    audience: "creators and teams selecting social-ready usernames",
    scenario: "building multiple handle options from one seed word",
    exampleInput: "seed: orbit",
    exampleOutput: "5-10 username variations for platform availability checks",
    pitfall: "finalizing handles without cross-platform consistency checks",
    interpretation: "choose options that remain readable and easy to spell",
    relatedIntent: "pair with brand and business naming for full identity setup",
    faq: [
      { question: "Can this generate professional and casual handles?", answer: "Yes, regenerate and shortlist based on intended platform tone." },
      { question: "Are outputs guaranteed unique?", answer: "No, availability depends on each platform at query time." },
      { question: "How many options are returned?", answer: "This tool returns between 5 and 10 options per run." },
    ],
  },
  "random-name-generator": {
    audience: "developers and designers creating mock or test name data",
    scenario: "producing batches of random names for prototypes and testing",
    exampleInput: "count: 8",
    exampleOutput: "8 random names with regenerate support for new sets",
    pitfall: "using unrealistic sample data that does not reflect target users",
    interpretation: "generate multiple sets and select names that match context",
    relatedIntent: "use with username and business name tools for identity mockups",
    faq: [
      { question: "Can I force exact count?", answer: "The generator is optimized for 5-10 outputs to keep results practical." },
      { question: "Does regenerate return different names?", answer: "Yes, each run randomizes output again." },
      { question: "Is this suitable for QA test data?", answer: "Yes, it is useful for non-sensitive placeholder data." },
    ],
  },
  "startup-name-generator": {
    audience: "startup founders exploring naming directions fast",
    scenario: "generating modern startup-style names from one niche keyword",
    exampleInput: "keyword: fintech",
    exampleOutput: "5-10 startup-oriented name combinations for shortlist",
    pitfall: "choosing trend-heavy names that age poorly",
    interpretation: "prioritize clarity, pronunciation, and long-term brand fit",
    relatedIntent: "pair with business and AI brand name tools for diverse options",
    faq: [
      { question: "Can I regenerate many rounds?", answer: "Yes, regenerate is intended for rapid ideation loops." },
      { question: "How many ideas are shown per generation?", answer: "Each generation returns 5-10 startup name ideas." },
      { question: "Should I include category keyword in final name?", answer: "Sometimes yes for clarity, but distinctiveness also matters." },
    ],
  },
  "brand-name-generator-ai": {
    audience: "brands and ecommerce teams creating tone-aligned naming options",
    scenario: "generating style-aware brand names from keyword and style selection",
    exampleInput: "keyword: skincare, style: premium",
    exampleOutput: "5-10 AI-assisted brand name suggestions in selected style",
    pitfall: "ignoring audience perception and pronunciation friction",
    interpretation: "test top candidates with target users before final lock-in",
    relatedIntent: "use alongside product description and social naming workflows",
    faq: [
      { question: "Does style selection change output feel?", answer: "Yes, style selection adjusts suffixes and naming texture." },
      { question: "Can I regenerate in same style?", answer: "Yes, regenerate keeps context while producing new combinations." },
      { question: "How many names are returned?", answer: "Each run returns between 5 and 10 brand name options." },
    ],
  },
  "time-zone-converter": {
    audience: "remote teams and global professionals coordinating cross-region schedules",
    scenario: "converting meeting times between UTC offsets quickly",
    exampleInput: "14:30 from UTC-5 to UTC+1",
    exampleOutput: "converted local time with offset difference context",
    pitfall: "forgetting to adjust offsets during daylight saving transitions",
    interpretation: "verify offsets for current season when scheduling high-stakes meetings",
    relatedIntent: "pair with date and age tools for timeline and planning utilities",
    faq: [
      { question: "Can I convert half-hour time zones?", answer: "Yes, offsets like +5.5 are supported." },
      { question: "Does this auto-handle DST?", answer: "Offsets are manual, so update values when DST changes." },
      { question: "Is 24-hour format required?", answer: "Yes, HH:MM in 24-hour format is required." },
    ],
  },
  "date-difference-calculator": {
    audience: "users tracking deadlines, billing periods, and project timelines",
    scenario: "calculating exact elapsed days and approximate months between two dates",
    exampleInput: "2026-01-01 to 2026-04-09",
    exampleOutput: "difference in days, weeks, months, and years approximation",
    pitfall: "assuming all months have equal day counts in manual calculations",
    interpretation: "use day-level output for precision and month output for planning estimates",
    relatedIntent: "combine with age and time-zone tools for date/time workflows",
    faq: [
      { question: "Does order of dates matter?", answer: "No, the calculator returns absolute difference." },
      { question: "Are leap years included?", answer: "Yes, actual calendar dates are used in calculations." },
      { question: "Can this compute business days?", answer: "This version provides total elapsed days, not business-day filters." },
    ],
  },
  "age-calculator": {
    audience: "people verifying age for forms, eligibility checks, and records",
    scenario: "calculating age from birth date to today or a custom as-of date",
    exampleInput: "birth 1995-08-15, as-of 2026-04-09",
    exampleOutput: "age in years, months, days with total-day context",
    pitfall: "manual month/day subtraction errors around month boundaries",
    interpretation: "use as-of date for historical/legal reference calculations",
    relatedIntent: "pair with date difference and unit conversion tools where needed",
    faq: [
      { question: "Can I calculate age on a specific date?", answer: "Yes, provide an as-of date to compute historical or future age." },
      { question: "Why do month/day values vary?", answer: "Calendar month lengths differ, affecting year-month-day breakdown." },
      { question: "Is this suitable for legal compliance checks?", answer: "Use as estimate and confirm against official rules where required." },
    ],
  },
  "unit-price-calculator": {
    audience: "shoppers and operators comparing true cost across package sizes",
    scenario: "calculating per-unit cost for value-based purchase decisions",
    exampleInput: "total price 12.99, quantity 3.5",
    exampleOutput: "unit price with clear quantity context",
    pitfall: "comparing products by sticker price instead of per-unit value",
    interpretation: "normalize all options to same unit before deciding",
    relatedIntent: "pair with discount calculator and monthly budget planning",
    faq: [
      { question: "Can quantity be fractional?", answer: "Yes, decimal quantities are supported for accurate pricing." },
      { question: "Should I include tax in total price?", answer: "Use tax-inclusive price if you want final consumer unit cost." },
      { question: "Can this compare subscription plans?", answer: "Yes, convert each plan to equivalent unit pricing." },
    ],
  },
  "discount-calculator": {
    audience: "consumers and sellers evaluating promotions and final checkout totals",
    scenario: "computing discount amount and final price after optional tax",
    exampleInput: "original 120, discount 25%, tax 8%",
    exampleOutput: "discount amount, discounted price, tax, and final payable",
    pitfall: "applying tax before discount in scenarios where discount is pre-tax",
    interpretation: "confirm store tax policy but use this for fast what-if comparisons",
    relatedIntent: "pair with unit price and budget planning for better purchase decisions",
    faq: [
      { question: "Can discount exceed 100%?", answer: "No, discount percentage must stay between 0 and 100." },
      { question: "Is tax optional?", answer: "Yes, leave tax at 0 if not needed." },
      { question: "Can this compare stacked offers?", answer: "Run scenarios separately to compare different offer structures." },
    ],
  },
};
