/** Representative small-claims limits (USD) and typical filing fees  -  verify with local courts. */
export const SMALL_CLAIMS_BY_STATE: Record<string, { limit: number; filingFee: number }> = {
  AL: { limit: 6000, filingFee: 55 },
  AK: { limit: 10000, filingFee: 60 },
  AZ: { limit: 3500, filingFee: 45 },
  AR: { limit: 5000, filingFee: 50 },
  CA: { limit: 10000, filingFee: 75 },
  CO: { limit: 7500, filingFee: 55 },
  CT: { limit: 5000, filingFee: 90 },
  DE: { limit: 25000, filingFee: 45 },
  FL: { limit: 8000, filingFee: 55 },
  GA: { limit: 15000, filingFee: 60 },
  HI: { limit: 5000, filingFee: 50 },
  ID: { limit: 5000, filingFee: 45 },
  IL: { limit: 10000, filingFee: 70 },
  IN: { limit: 6000, filingFee: 50 },
  IA: { limit: 6500, filingFee: 50 },
  KS: { limit: 4000, filingFee: 45 },
  KY: { limit: 2500, filingFee: 40 },
  LA: { limit: 5000, filingFee: 50 },
  ME: { limit: 6000, filingFee: 55 },
  MD: { limit: 5000, filingFee: 65 },
  MA: { limit: 7000, filingFee: 50 },
  MI: { limit: 6500, filingFee: 60 },
  MN: { limit: 15000, filingFee: 70 },
  MS: { limit: 3500, filingFee: 45 },
  MO: { limit: 5000, filingFee: 50 },
  MT: { limit: 7000, filingFee: 50 },
  NE: { limit: 3900, filingFee: 45 },
  NV: { limit: 10000, filingFee: 65 },
  NH: { limit: 10000, filingFee: 90 },
  NJ: { limit: 3000, filingFee: 50 },
  NM: { limit: 10000, filingFee: 55 },
  NY: { limit: 5000, filingFee: 45 },
  NC: { limit: 10000, filingFee: 96 },
  ND: { limit: 15000, filingFee: 50 },
  OH: { limit: 6000, filingFee: 55 },
  OK: { limit: 10000, filingFee: 50 },
  OR: { limit: 10000, filingFee: 57 },
  PA: { limit: 12000, filingFee: 95 },
  RI: { limit: 2500, filingFee: 60 },
  SC: { limit: 7500, filingFee: 70 },
  SD: { limit: 12000, filingFee: 70 },
  TN: { limit: 25000, filingFee: 65 },
  TX: { limit: 20000, filingFee: 54 },
  UT: { limit: 15000, filingFee: 60 },
  VT: { limit: 5000, filingFee: 65 },
  VA: { limit: 5000, filingFee: 50 },
  WA: { limit: 10000, filingFee: 50 },
  WV: { limit: 5000, filingFee: 45 },
  WI: { limit: 10000, filingFee: 94 },
  WY: { limit: 6000, filingFee: 55 },
};

const STATE_NAMES: Record<string, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
};

export const SMALL_CLAIMS_STATE_OPTIONS = Object.keys(SMALL_CLAIMS_BY_STATE)
  .sort((a, b) => STATE_NAMES[a].localeCompare(STATE_NAMES[b]))
  .map((code) => ({ label: `${STATE_NAMES[code]} (${code})`, value: code }));
